// Auto-generated by LibreLane
module butterfold_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_ni,
  input[7:0] din,
  input din_valid_i,
  output din_ready_o,
  output[7:0] dout,
  output dout_valid_o,
  input dout_ready_i,
  output done_irq_o,
  input scan_en_i,
  input scan_in_i,
  output scan_out_o
);
endmodule
