// ButterFold Reference Implementation  —  GENERATED by gen_reference.py
// DFT-s-OFDM TX core: 12-pt DFT -> centered map -> 128-pt IFFT -> CP -> 274 bytes
//
// FOLDED minimum-area datapath: every complex multiply-accumulate (144 for the DFT,
// 12 per output sample for the IFFT) is time-multiplexed onto ONE shared complex
// multiplier, with two twiddle ROMs (W12 forward, W128 inverse). Throughput is
// traded for a single reused datapath — the core ButterFold architecture.
//
// Validated against butterfold_sim: Stage-6 seed (42) golden-model EVM < 2%.
// Do not hand-edit; regenerate via gen_reference.py instead.
//
// Frozen params: K=12, M=128, CP=9, centered START=58, twiddle bits A=B=9, SHIFT=25

`timescale 1ns/1ps
module butterfold_top (
  input  wire        clk,
  input  wire        rst_n,
  input  wire        mode,        // 0 = TX (golden path), 1 = RX
  input  wire  [7:0] din,
  input  wire        din_valid,
  output reg   [7:0] dout,
  output reg         dout_valid,
  output reg         busy,
  output reg         done
);

  // ── FSM states ──────────────────────────────────────────────────────────
  // Folded schedule: every complex multiply-accumulate is time-multiplexed
  // onto ONE shared complex multiplier (mult_pr/mult_pi below). This is the
  // minimum-area architecture ButterFold targets — throughput is traded for a
  // single reused datapath.
  localparam S_IDLE = 3'd0;
  localparam S_LOAD = 3'd1;   // capture 24 input bytes (12 complex symbols)
  localparam S_DFT  = 3'd2;   // 12x12 MACs -> 12 spread bins (one MAC/cycle)
  localparam S_IFFT = 3'd3;   // 12 MACs per output sample (one MAC/cycle)
  localparam S_EMIT = 3'd4;   // stream the sample's I then Q byte

  reg [2:0]  state;
  reg [4:0]  load_cnt;        // 0..23
  reg [3:0]  dft_j, dft_n;    // DFT outer/inner indices 0..11
  reg [7:0]  samp;            // current output sample 0..136
  reg [3:0]  ifft_j;          // IFFT accumulation index 0..11
  reg        emit_half;       // 0 = emit I byte, 1 = emit Q byte

  // ── Input buffer (24 signed bytes) ──────────────────────────────────────
  // (* mem2reg *) forces flip-flop inference instead of a RAM write-port model,
  // which avoids the benign "$mem$...wr$...DATA has no driver" synth warnings.
  (* mem2reg *) reg signed [7:0] inbuf [0:23];

  // ── DFT result: 12 complex spread bins (sized to worst case) ────────────
  (* mem2reg *) reg signed [23:0] spread_re [0:11];
  (* mem2reg *) reg signed [23:0] spread_im [0:11];

  // ── Shared accumulator and pending output bytes ─────────────────────────
  reg signed [39:0] acc_re, acc_im;
  reg signed [7:0]  out_i_byte, out_q_byte;

  // ── Twiddle ROMs + (n*j) mod 12 LUT (combinational, synthesizable) ──────
  function signed [11:0] w12_re;
    input [3:0] idx;
    case (idx)
      4'd0: w12_re = 12'sd512;
      4'd1: w12_re = 12'sd443;
      4'd2: w12_re = 12'sd256;
      4'd3: w12_re = 12'sd0;
      4'd4: w12_re = -12'sd256;
      4'd5: w12_re = -12'sd443;
      4'd6: w12_re = -12'sd512;
      4'd7: w12_re = -12'sd443;
      4'd8: w12_re = -12'sd256;
      4'd9: w12_re = 12'sd0;
      4'd10: w12_re = 12'sd256;
      4'd11: w12_re = 12'sd443;
      default: w12_re = 12'sd0;
    endcase
  endfunction

  function signed [11:0] w12_im;
    input [3:0] idx;
    case (idx)
      4'd0: w12_im = 12'sd0;
      4'd1: w12_im = -12'sd256;
      4'd2: w12_im = -12'sd443;
      4'd3: w12_im = -12'sd512;
      4'd4: w12_im = -12'sd443;
      4'd5: w12_im = -12'sd256;
      4'd6: w12_im = 12'sd0;
      4'd7: w12_im = 12'sd256;
      4'd8: w12_im = 12'sd443;
      4'd9: w12_im = 12'sd512;
      4'd10: w12_im = 12'sd443;
      4'd11: w12_im = 12'sd256;
      default: w12_im = 12'sd0;
    endcase
  endfunction

  function signed [11:0] w128_re;
    input [6:0] idx;
    case (idx)
      7'd0: w128_re = 12'sd512;
      7'd1: w128_re = 12'sd511;
      7'd2: w128_re = 12'sd510;
      7'd3: w128_re = 12'sd506;
      7'd4: w128_re = 12'sd502;
      7'd5: w128_re = 12'sd497;
      7'd6: w128_re = 12'sd490;
      7'd7: w128_re = 12'sd482;
      7'd8: w128_re = 12'sd473;
      7'd9: w128_re = 12'sd463;
      7'd10: w128_re = 12'sd452;
      7'd11: w128_re = 12'sd439;
      7'd12: w128_re = 12'sd426;
      7'd13: w128_re = 12'sd411;
      7'd14: w128_re = 12'sd396;
      7'd15: w128_re = 12'sd379;
      7'd16: w128_re = 12'sd362;
      7'd17: w128_re = 12'sd344;
      7'd18: w128_re = 12'sd325;
      7'd19: w128_re = 12'sd305;
      7'd20: w128_re = 12'sd284;
      7'd21: w128_re = 12'sd263;
      7'd22: w128_re = 12'sd241;
      7'd23: w128_re = 12'sd219;
      7'd24: w128_re = 12'sd196;
      7'd25: w128_re = 12'sd172;
      7'd26: w128_re = 12'sd149;
      7'd27: w128_re = 12'sd124;
      7'd28: w128_re = 12'sd100;
      7'd29: w128_re = 12'sd75;
      7'd30: w128_re = 12'sd50;
      7'd31: w128_re = 12'sd25;
      7'd32: w128_re = 12'sd0;
      7'd33: w128_re = -12'sd25;
      7'd34: w128_re = -12'sd50;
      7'd35: w128_re = -12'sd75;
      7'd36: w128_re = -12'sd100;
      7'd37: w128_re = -12'sd124;
      7'd38: w128_re = -12'sd149;
      7'd39: w128_re = -12'sd172;
      7'd40: w128_re = -12'sd196;
      7'd41: w128_re = -12'sd219;
      7'd42: w128_re = -12'sd241;
      7'd43: w128_re = -12'sd263;
      7'd44: w128_re = -12'sd284;
      7'd45: w128_re = -12'sd305;
      7'd46: w128_re = -12'sd325;
      7'd47: w128_re = -12'sd344;
      7'd48: w128_re = -12'sd362;
      7'd49: w128_re = -12'sd379;
      7'd50: w128_re = -12'sd396;
      7'd51: w128_re = -12'sd411;
      7'd52: w128_re = -12'sd426;
      7'd53: w128_re = -12'sd439;
      7'd54: w128_re = -12'sd452;
      7'd55: w128_re = -12'sd463;
      7'd56: w128_re = -12'sd473;
      7'd57: w128_re = -12'sd482;
      7'd58: w128_re = -12'sd490;
      7'd59: w128_re = -12'sd497;
      7'd60: w128_re = -12'sd502;
      7'd61: w128_re = -12'sd506;
      7'd62: w128_re = -12'sd510;
      7'd63: w128_re = -12'sd511;
      7'd64: w128_re = -12'sd512;
      7'd65: w128_re = -12'sd511;
      7'd66: w128_re = -12'sd510;
      7'd67: w128_re = -12'sd506;
      7'd68: w128_re = -12'sd502;
      7'd69: w128_re = -12'sd497;
      7'd70: w128_re = -12'sd490;
      7'd71: w128_re = -12'sd482;
      7'd72: w128_re = -12'sd473;
      7'd73: w128_re = -12'sd463;
      7'd74: w128_re = -12'sd452;
      7'd75: w128_re = -12'sd439;
      7'd76: w128_re = -12'sd426;
      7'd77: w128_re = -12'sd411;
      7'd78: w128_re = -12'sd396;
      7'd79: w128_re = -12'sd379;
      7'd80: w128_re = -12'sd362;
      7'd81: w128_re = -12'sd344;
      7'd82: w128_re = -12'sd325;
      7'd83: w128_re = -12'sd305;
      7'd84: w128_re = -12'sd284;
      7'd85: w128_re = -12'sd263;
      7'd86: w128_re = -12'sd241;
      7'd87: w128_re = -12'sd219;
      7'd88: w128_re = -12'sd196;
      7'd89: w128_re = -12'sd172;
      7'd90: w128_re = -12'sd149;
      7'd91: w128_re = -12'sd124;
      7'd92: w128_re = -12'sd100;
      7'd93: w128_re = -12'sd75;
      7'd94: w128_re = -12'sd50;
      7'd95: w128_re = -12'sd25;
      7'd96: w128_re = 12'sd0;
      7'd97: w128_re = 12'sd25;
      7'd98: w128_re = 12'sd50;
      7'd99: w128_re = 12'sd75;
      7'd100: w128_re = 12'sd100;
      7'd101: w128_re = 12'sd124;
      7'd102: w128_re = 12'sd149;
      7'd103: w128_re = 12'sd172;
      7'd104: w128_re = 12'sd196;
      7'd105: w128_re = 12'sd219;
      7'd106: w128_re = 12'sd241;
      7'd107: w128_re = 12'sd263;
      7'd108: w128_re = 12'sd284;
      7'd109: w128_re = 12'sd305;
      7'd110: w128_re = 12'sd325;
      7'd111: w128_re = 12'sd344;
      7'd112: w128_re = 12'sd362;
      7'd113: w128_re = 12'sd379;
      7'd114: w128_re = 12'sd396;
      7'd115: w128_re = 12'sd411;
      7'd116: w128_re = 12'sd426;
      7'd117: w128_re = 12'sd439;
      7'd118: w128_re = 12'sd452;
      7'd119: w128_re = 12'sd463;
      7'd120: w128_re = 12'sd473;
      7'd121: w128_re = 12'sd482;
      7'd122: w128_re = 12'sd490;
      7'd123: w128_re = 12'sd497;
      7'd124: w128_re = 12'sd502;
      7'd125: w128_re = 12'sd506;
      7'd126: w128_re = 12'sd510;
      7'd127: w128_re = 12'sd511;
      default: w128_re = 12'sd0;
    endcase
  endfunction

  function signed [11:0] w128_im;
    input [6:0] idx;
    case (idx)
      7'd0: w128_im = 12'sd0;
      7'd1: w128_im = 12'sd25;
      7'd2: w128_im = 12'sd50;
      7'd3: w128_im = 12'sd75;
      7'd4: w128_im = 12'sd100;
      7'd5: w128_im = 12'sd124;
      7'd6: w128_im = 12'sd149;
      7'd7: w128_im = 12'sd172;
      7'd8: w128_im = 12'sd196;
      7'd9: w128_im = 12'sd219;
      7'd10: w128_im = 12'sd241;
      7'd11: w128_im = 12'sd263;
      7'd12: w128_im = 12'sd284;
      7'd13: w128_im = 12'sd305;
      7'd14: w128_im = 12'sd325;
      7'd15: w128_im = 12'sd344;
      7'd16: w128_im = 12'sd362;
      7'd17: w128_im = 12'sd379;
      7'd18: w128_im = 12'sd396;
      7'd19: w128_im = 12'sd411;
      7'd20: w128_im = 12'sd426;
      7'd21: w128_im = 12'sd439;
      7'd22: w128_im = 12'sd452;
      7'd23: w128_im = 12'sd463;
      7'd24: w128_im = 12'sd473;
      7'd25: w128_im = 12'sd482;
      7'd26: w128_im = 12'sd490;
      7'd27: w128_im = 12'sd497;
      7'd28: w128_im = 12'sd502;
      7'd29: w128_im = 12'sd506;
      7'd30: w128_im = 12'sd510;
      7'd31: w128_im = 12'sd511;
      7'd32: w128_im = 12'sd512;
      7'd33: w128_im = 12'sd511;
      7'd34: w128_im = 12'sd510;
      7'd35: w128_im = 12'sd506;
      7'd36: w128_im = 12'sd502;
      7'd37: w128_im = 12'sd497;
      7'd38: w128_im = 12'sd490;
      7'd39: w128_im = 12'sd482;
      7'd40: w128_im = 12'sd473;
      7'd41: w128_im = 12'sd463;
      7'd42: w128_im = 12'sd452;
      7'd43: w128_im = 12'sd439;
      7'd44: w128_im = 12'sd426;
      7'd45: w128_im = 12'sd411;
      7'd46: w128_im = 12'sd396;
      7'd47: w128_im = 12'sd379;
      7'd48: w128_im = 12'sd362;
      7'd49: w128_im = 12'sd344;
      7'd50: w128_im = 12'sd325;
      7'd51: w128_im = 12'sd305;
      7'd52: w128_im = 12'sd284;
      7'd53: w128_im = 12'sd263;
      7'd54: w128_im = 12'sd241;
      7'd55: w128_im = 12'sd219;
      7'd56: w128_im = 12'sd196;
      7'd57: w128_im = 12'sd172;
      7'd58: w128_im = 12'sd149;
      7'd59: w128_im = 12'sd124;
      7'd60: w128_im = 12'sd100;
      7'd61: w128_im = 12'sd75;
      7'd62: w128_im = 12'sd50;
      7'd63: w128_im = 12'sd25;
      7'd64: w128_im = 12'sd0;
      7'd65: w128_im = -12'sd25;
      7'd66: w128_im = -12'sd50;
      7'd67: w128_im = -12'sd75;
      7'd68: w128_im = -12'sd100;
      7'd69: w128_im = -12'sd124;
      7'd70: w128_im = -12'sd149;
      7'd71: w128_im = -12'sd172;
      7'd72: w128_im = -12'sd196;
      7'd73: w128_im = -12'sd219;
      7'd74: w128_im = -12'sd241;
      7'd75: w128_im = -12'sd263;
      7'd76: w128_im = -12'sd284;
      7'd77: w128_im = -12'sd305;
      7'd78: w128_im = -12'sd325;
      7'd79: w128_im = -12'sd344;
      7'd80: w128_im = -12'sd362;
      7'd81: w128_im = -12'sd379;
      7'd82: w128_im = -12'sd396;
      7'd83: w128_im = -12'sd411;
      7'd84: w128_im = -12'sd426;
      7'd85: w128_im = -12'sd439;
      7'd86: w128_im = -12'sd452;
      7'd87: w128_im = -12'sd463;
      7'd88: w128_im = -12'sd473;
      7'd89: w128_im = -12'sd482;
      7'd90: w128_im = -12'sd490;
      7'd91: w128_im = -12'sd497;
      7'd92: w128_im = -12'sd502;
      7'd93: w128_im = -12'sd506;
      7'd94: w128_im = -12'sd510;
      7'd95: w128_im = -12'sd511;
      7'd96: w128_im = -12'sd512;
      7'd97: w128_im = -12'sd511;
      7'd98: w128_im = -12'sd510;
      7'd99: w128_im = -12'sd506;
      7'd100: w128_im = -12'sd502;
      7'd101: w128_im = -12'sd497;
      7'd102: w128_im = -12'sd490;
      7'd103: w128_im = -12'sd482;
      7'd104: w128_im = -12'sd473;
      7'd105: w128_im = -12'sd463;
      7'd106: w128_im = -12'sd452;
      7'd107: w128_im = -12'sd439;
      7'd108: w128_im = -12'sd426;
      7'd109: w128_im = -12'sd411;
      7'd110: w128_im = -12'sd396;
      7'd111: w128_im = -12'sd379;
      7'd112: w128_im = -12'sd362;
      7'd113: w128_im = -12'sd344;
      7'd114: w128_im = -12'sd325;
      7'd115: w128_im = -12'sd305;
      7'd116: w128_im = -12'sd284;
      7'd117: w128_im = -12'sd263;
      7'd118: w128_im = -12'sd241;
      7'd119: w128_im = -12'sd219;
      7'd120: w128_im = -12'sd196;
      7'd121: w128_im = -12'sd172;
      7'd122: w128_im = -12'sd149;
      7'd123: w128_im = -12'sd124;
      7'd124: w128_im = -12'sd100;
      7'd125: w128_im = -12'sd75;
      7'd126: w128_im = -12'sd50;
      7'd127: w128_im = -12'sd25;
      default: w128_im = 12'sd0;
    endcase
  endfunction

  function [3:0] idx12;
    input [3:0] nn;
    input [3:0] jj;
    case ({nn, jj})
      8'h00: idx12 = 4'd0;
      8'h01: idx12 = 4'd0;
      8'h02: idx12 = 4'd0;
      8'h03: idx12 = 4'd0;
      8'h04: idx12 = 4'd0;
      8'h05: idx12 = 4'd0;
      8'h06: idx12 = 4'd0;
      8'h07: idx12 = 4'd0;
      8'h08: idx12 = 4'd0;
      8'h09: idx12 = 4'd0;
      8'h0a: idx12 = 4'd0;
      8'h0b: idx12 = 4'd0;
      8'h10: idx12 = 4'd0;
      8'h11: idx12 = 4'd1;
      8'h12: idx12 = 4'd2;
      8'h13: idx12 = 4'd3;
      8'h14: idx12 = 4'd4;
      8'h15: idx12 = 4'd5;
      8'h16: idx12 = 4'd6;
      8'h17: idx12 = 4'd7;
      8'h18: idx12 = 4'd8;
      8'h19: idx12 = 4'd9;
      8'h1a: idx12 = 4'd10;
      8'h1b: idx12 = 4'd11;
      8'h20: idx12 = 4'd0;
      8'h21: idx12 = 4'd2;
      8'h22: idx12 = 4'd4;
      8'h23: idx12 = 4'd6;
      8'h24: idx12 = 4'd8;
      8'h25: idx12 = 4'd10;
      8'h26: idx12 = 4'd0;
      8'h27: idx12 = 4'd2;
      8'h28: idx12 = 4'd4;
      8'h29: idx12 = 4'd6;
      8'h2a: idx12 = 4'd8;
      8'h2b: idx12 = 4'd10;
      8'h30: idx12 = 4'd0;
      8'h31: idx12 = 4'd3;
      8'h32: idx12 = 4'd6;
      8'h33: idx12 = 4'd9;
      8'h34: idx12 = 4'd0;
      8'h35: idx12 = 4'd3;
      8'h36: idx12 = 4'd6;
      8'h37: idx12 = 4'd9;
      8'h38: idx12 = 4'd0;
      8'h39: idx12 = 4'd3;
      8'h3a: idx12 = 4'd6;
      8'h3b: idx12 = 4'd9;
      8'h40: idx12 = 4'd0;
      8'h41: idx12 = 4'd4;
      8'h42: idx12 = 4'd8;
      8'h43: idx12 = 4'd0;
      8'h44: idx12 = 4'd4;
      8'h45: idx12 = 4'd8;
      8'h46: idx12 = 4'd0;
      8'h47: idx12 = 4'd4;
      8'h48: idx12 = 4'd8;
      8'h49: idx12 = 4'd0;
      8'h4a: idx12 = 4'd4;
      8'h4b: idx12 = 4'd8;
      8'h50: idx12 = 4'd0;
      8'h51: idx12 = 4'd5;
      8'h52: idx12 = 4'd10;
      8'h53: idx12 = 4'd3;
      8'h54: idx12 = 4'd8;
      8'h55: idx12 = 4'd1;
      8'h56: idx12 = 4'd6;
      8'h57: idx12 = 4'd11;
      8'h58: idx12 = 4'd4;
      8'h59: idx12 = 4'd9;
      8'h5a: idx12 = 4'd2;
      8'h5b: idx12 = 4'd7;
      8'h60: idx12 = 4'd0;
      8'h61: idx12 = 4'd6;
      8'h62: idx12 = 4'd0;
      8'h63: idx12 = 4'd6;
      8'h64: idx12 = 4'd0;
      8'h65: idx12 = 4'd6;
      8'h66: idx12 = 4'd0;
      8'h67: idx12 = 4'd6;
      8'h68: idx12 = 4'd0;
      8'h69: idx12 = 4'd6;
      8'h6a: idx12 = 4'd0;
      8'h6b: idx12 = 4'd6;
      8'h70: idx12 = 4'd0;
      8'h71: idx12 = 4'd7;
      8'h72: idx12 = 4'd2;
      8'h73: idx12 = 4'd9;
      8'h74: idx12 = 4'd4;
      8'h75: idx12 = 4'd11;
      8'h76: idx12 = 4'd6;
      8'h77: idx12 = 4'd1;
      8'h78: idx12 = 4'd8;
      8'h79: idx12 = 4'd3;
      8'h7a: idx12 = 4'd10;
      8'h7b: idx12 = 4'd5;
      8'h80: idx12 = 4'd0;
      8'h81: idx12 = 4'd8;
      8'h82: idx12 = 4'd4;
      8'h83: idx12 = 4'd0;
      8'h84: idx12 = 4'd8;
      8'h85: idx12 = 4'd4;
      8'h86: idx12 = 4'd0;
      8'h87: idx12 = 4'd8;
      8'h88: idx12 = 4'd4;
      8'h89: idx12 = 4'd0;
      8'h8a: idx12 = 4'd8;
      8'h8b: idx12 = 4'd4;
      8'h90: idx12 = 4'd0;
      8'h91: idx12 = 4'd9;
      8'h92: idx12 = 4'd6;
      8'h93: idx12 = 4'd3;
      8'h94: idx12 = 4'd0;
      8'h95: idx12 = 4'd9;
      8'h96: idx12 = 4'd6;
      8'h97: idx12 = 4'd3;
      8'h98: idx12 = 4'd0;
      8'h99: idx12 = 4'd9;
      8'h9a: idx12 = 4'd6;
      8'h9b: idx12 = 4'd3;
      8'ha0: idx12 = 4'd0;
      8'ha1: idx12 = 4'd10;
      8'ha2: idx12 = 4'd8;
      8'ha3: idx12 = 4'd6;
      8'ha4: idx12 = 4'd4;
      8'ha5: idx12 = 4'd2;
      8'ha6: idx12 = 4'd0;
      8'ha7: idx12 = 4'd10;
      8'ha8: idx12 = 4'd8;
      8'ha9: idx12 = 4'd6;
      8'haa: idx12 = 4'd4;
      8'hab: idx12 = 4'd2;
      8'hb0: idx12 = 4'd0;
      8'hb1: idx12 = 4'd11;
      8'hb2: idx12 = 4'd10;
      8'hb3: idx12 = 4'd9;
      8'hb4: idx12 = 4'd8;
      8'hb5: idx12 = 4'd7;
      8'hb6: idx12 = 4'd6;
      8'hb7: idx12 = 4'd5;
      8'hb8: idx12 = 4'd4;
      8'hb9: idx12 = 4'd3;
      8'hba: idx12 = 4'd2;
      8'hbb: idx12 = 4'd1;
      default: idx12 = 4'd0;
    endcase
  endfunction

  // ── ONE shared complex multiplier ───────────────────────────────────────
  // Operands are muxed by the FSM: DFT uses (inbuf, W12); IFFT uses (spread, W128).
  reg signed [23:0] mult_ar, mult_ai;   // holds inbuf(8b) and spread
  reg signed [11:0]     mult_br, mult_bi;   // twiddle word
  reg  [3:0] d12;                        // (n*j) mod 12 (from LUT, no divider)
  reg  [6:0] tau;                        // IFFT time index (CP-adjusted)
  reg  [6:0] w_idx;                      // ((START+j)*tau) mod 128

  always @(*) begin
    d12     = idx12(dft_n, dft_j);
    tau     = (samp < 9) ? (samp + 119) : (samp - 9);
    w_idx   = (((58 + ifft_j) * tau) & 7'h7f);
    if (state == S_DFT) begin
      mult_ar = inbuf[2*dft_n];
      mult_ai = inbuf[2*dft_n + 1];
      mult_br = w12_re(d12);
      mult_bi = w12_im(d12);
    end else begin   // S_IFFT
      mult_ar = spread_re[ifft_j];
      mult_ai = spread_im[ifft_j];
      mult_br = w128_re(w_idx);
      mult_bi = w128_im(w_idx);
    end
  end

  // The single complex multiplier (4 real multiplies, reused every cycle)
  wire signed [39:0] mult_pr = mult_ar * mult_br - mult_ai * mult_bi;
  wire signed [39:0] mult_pi = mult_ar * mult_bi + mult_ai * mult_br;

  // Full sums for the final term of an accumulation
  wire signed [39:0] fin_re = acc_re + mult_pr;
  wire signed [39:0] fin_im = acc_im + mult_pi;

  // Round-shift + saturate to int8 (for the final IFFT term)
  wire signed [39:0] shr_re = (fin_re + (40'sd1 <<< (25 - 1))) >>> 25;
  wire signed [39:0] shr_im = (fin_im + (40'sd1 <<< (25 - 1))) >>> 25;
  wire signed [7:0]  fbyte_re =
      (shr_re >  40'sd127) ?  8'sd127 : (shr_re < -40'sd128) ? -8'sd128 : shr_re[7:0];
  wire signed [7:0]  fbyte_im =
      (shr_im >  40'sd127) ?  8'sd127 : (shr_im < -40'sd128) ? -8'sd128 : shr_im[7:0];

  // ── Single sequential FSM (drives all state) ────────────────────────────
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state      <= S_IDLE;
      load_cnt   <= 5'd0;
      dft_j      <= 4'd0;
      dft_n      <= 4'd0;
      samp       <= 8'd0;
      ifft_j     <= 4'd0;
      emit_half  <= 1'b0;
      acc_re     <= 40'sd0;
      acc_im     <= 40'sd0;
      out_i_byte <= 8'sd0;
      out_q_byte <= 8'sd0;
      dout       <= 8'd0;
      dout_valid <= 1'b0;
      busy       <= 1'b0;
      done       <= 1'b0;
    end else begin
      done       <= 1'b0;
      dout_valid <= 1'b0;

      case (state)
        S_IDLE: begin
          busy <= 1'b0;
          if (din_valid) begin
            inbuf[0] <= din;
            load_cnt <= 5'd1;
            busy     <= 1'b1;
            state    <= S_LOAD;
          end
        end

        S_LOAD: begin
          busy <= 1'b1;
          inbuf[load_cnt] <= din;
          if (load_cnt == 5'd23) begin
            load_cnt <= 5'd0;
            dft_j    <= 4'd0;
            dft_n    <= 4'd0;
            acc_re   <= 64'sd0;
            acc_im   <= 64'sd0;
            state    <= S_DFT;
          end else begin
            load_cnt <= load_cnt + 5'd1;
          end
        end

        // 12-point DFT: spread[j] = sum_n symbol[n] * W12[(n*j) mod 12]
        S_DFT: begin
          busy <= 1'b1;
          if (dft_n == 4'd11) begin
            spread_re[dft_j] <= fin_re[23:0];   // last term + store
            spread_im[dft_j] <= fin_im[23:0];
            acc_re <= 40'sd0;
            acc_im <= 40'sd0;
            dft_n  <= 4'd0;
            if (dft_j == 4'd11) begin
              dft_j  <= 4'd0;
              samp   <= 8'd0;
              ifft_j <= 4'd0;
              state  <= S_IFFT;
            end else begin
              dft_j <= dft_j + 4'd1;
            end
          end else begin
            acc_re <= acc_re + mult_pr;
            acc_im <= acc_im + mult_pi;
            dft_n  <= dft_n + 4'd1;
          end
        end

        // IFFT (centered map + CP): time[samp] = sum_j spread[j] * W128[(START+j)*tau]
        S_IFFT: begin
          busy <= 1'b1;
          if (ifft_j == 4'd11) begin
            out_i_byte <= fbyte_re;             // round/saturate the full sum
            out_q_byte <= fbyte_im;
            acc_re     <= 64'sd0;
            acc_im     <= 64'sd0;
            ifft_j     <= 4'd0;
            emit_half  <= 1'b0;
            state      <= S_EMIT;
          end else begin
            acc_re <= acc_re + mult_pr;
            acc_im <= acc_im + mult_pi;
            ifft_j <= ifft_j + 4'd1;
          end
        end

        // Stream I then Q for the current sample
        S_EMIT: begin
          busy       <= 1'b1;
          dout_valid <= 1'b1;
          if (emit_half == 1'b0) begin
            dout      <= out_i_byte;
            emit_half <= 1'b1;
          end else begin
            dout      <= out_q_byte;
            emit_half <= 1'b0;
            if (samp == 136) begin         // 136 = last sample
              state <= S_IDLE;
              done  <= 1'b1;
            end else begin
              samp   <= samp + 8'd1;
              ifft_j <= 4'd0;
              state  <= S_IFFT;
            end
          end
        end

        default: state <= S_IDLE;
      endcase
    end
  end

endmodule
