// ButterFold Reference Implementation  —  GENERATED by gen_reference.py
// DFT-s-OFDM TX core: 12-pt DFT -> centered map -> 128-pt IFFT -> CP -> 274 bytes
//
// Two real twiddle ROMs (W12 for the DFT, W128 for the IFFT) implement the folded
// mixed-radix transform chain in int8 fixed point. Validated against butterfold_sim:
// Stage-6 seed (42) golden-model EVM < 2%.  Do not hand-edit; regenerate instead.
//
// Frozen params: K=12, M=128, CP=9, centered START=58, twiddle bits A=B=12, SHIFT=31

`timescale 1ns/1ps
module butterfold_top (
  input  wire        clk,
  input  wire        rst_n,
  input  wire        mode,        // 0 = TX (golden path), 1 = RX
  input  wire  [7:0] din,
  input  wire        din_valid,
  output reg   [7:0] dout,
  output reg         dout_valid,
  output reg         busy,
  output reg         done
);

  // ── FSM states ──────────────────────────────────────────────────────────
  localparam S_IDLE   = 2'd0;
  localparam S_LOAD   = 2'd1;   // capture 24 input bytes (12 complex symbols)
  localparam S_DFT    = 2'd2;   // compute 12 spread bins
  localparam S_STREAM = 2'd3;   // emit 274 output bytes (IFFT + CP, on the fly)

  reg [1:0]  state;
  reg [4:0]  load_cnt;          // 0..23
  reg [8:0]  out_cnt;           // 0..273

  // ── Input buffer (24 signed bytes) ──────────────────────────────────────
  reg signed [7:0] buf [0:23];

  // ── DFT result: 12 complex spread bins (wide accumulators) ──────────────
  reg signed [31:0] spread_re [0:11];
  reg signed [31:0] spread_im [0:11];

  integer cj;            // loop var for the combinational IFFT block
  integer dn, dj;        // loop vars for the sequential DFT block

  // ── Twiddle ROMs (combinational, synthesizable case statements) ─────────
  function signed [15:0] w12_re;
    input [3:0] idx;
    case (idx)
      4'd0: w12_re = 16'sd4096;
      4'd1: w12_re = 16'sd3547;
      4'd2: w12_re = 16'sd2048;
      4'd3: w12_re = 16'sd0;
      4'd4: w12_re = -16'sd2048;
      4'd5: w12_re = -16'sd3547;
      4'd6: w12_re = -16'sd4096;
      4'd7: w12_re = -16'sd3547;
      4'd8: w12_re = -16'sd2048;
      4'd9: w12_re = 16'sd0;
      4'd10: w12_re = 16'sd2048;
      4'd11: w12_re = 16'sd3547;
      default: w12_re = 16'sd0;
    endcase
  endfunction

  function signed [15:0] w12_im;
    input [3:0] idx;
    case (idx)
      4'd0: w12_im = 16'sd0;
      4'd1: w12_im = -16'sd2048;
      4'd2: w12_im = -16'sd3547;
      4'd3: w12_im = -16'sd4096;
      4'd4: w12_im = -16'sd3547;
      4'd5: w12_im = -16'sd2048;
      4'd6: w12_im = 16'sd0;
      4'd7: w12_im = 16'sd2048;
      4'd8: w12_im = 16'sd3547;
      4'd9: w12_im = 16'sd4096;
      4'd10: w12_im = 16'sd3547;
      4'd11: w12_im = 16'sd2048;
      default: w12_im = 16'sd0;
    endcase
  endfunction

  function signed [15:0] w128_re;
    input [6:0] idx;
    case (idx)
      7'd0: w128_re = 16'sd4096;
      7'd1: w128_re = 16'sd4091;
      7'd2: w128_re = 16'sd4076;
      7'd3: w128_re = 16'sd4052;
      7'd4: w128_re = 16'sd4017;
      7'd5: w128_re = 16'sd3973;
      7'd6: w128_re = 16'sd3920;
      7'd7: w128_re = 16'sd3857;
      7'd8: w128_re = 16'sd3784;
      7'd9: w128_re = 16'sd3703;
      7'd10: w128_re = 16'sd3612;
      7'd11: w128_re = 16'sd3513;
      7'd12: w128_re = 16'sd3406;
      7'd13: w128_re = 16'sd3290;
      7'd14: w128_re = 16'sd3166;
      7'd15: w128_re = 16'sd3035;
      7'd16: w128_re = 16'sd2896;
      7'd17: w128_re = 16'sd2751;
      7'd18: w128_re = 16'sd2598;
      7'd19: w128_re = 16'sd2440;
      7'd20: w128_re = 16'sd2276;
      7'd21: w128_re = 16'sd2106;
      7'd22: w128_re = 16'sd1931;
      7'd23: w128_re = 16'sd1751;
      7'd24: w128_re = 16'sd1567;
      7'd25: w128_re = 16'sd1380;
      7'd26: w128_re = 16'sd1189;
      7'd27: w128_re = 16'sd995;
      7'd28: w128_re = 16'sd799;
      7'd29: w128_re = 16'sd601;
      7'd30: w128_re = 16'sd401;
      7'd31: w128_re = 16'sd201;
      7'd32: w128_re = 16'sd0;
      7'd33: w128_re = -16'sd201;
      7'd34: w128_re = -16'sd401;
      7'd35: w128_re = -16'sd601;
      7'd36: w128_re = -16'sd799;
      7'd37: w128_re = -16'sd995;
      7'd38: w128_re = -16'sd1189;
      7'd39: w128_re = -16'sd1380;
      7'd40: w128_re = -16'sd1567;
      7'd41: w128_re = -16'sd1751;
      7'd42: w128_re = -16'sd1931;
      7'd43: w128_re = -16'sd2106;
      7'd44: w128_re = -16'sd2276;
      7'd45: w128_re = -16'sd2440;
      7'd46: w128_re = -16'sd2598;
      7'd47: w128_re = -16'sd2751;
      7'd48: w128_re = -16'sd2896;
      7'd49: w128_re = -16'sd3035;
      7'd50: w128_re = -16'sd3166;
      7'd51: w128_re = -16'sd3290;
      7'd52: w128_re = -16'sd3406;
      7'd53: w128_re = -16'sd3513;
      7'd54: w128_re = -16'sd3612;
      7'd55: w128_re = -16'sd3703;
      7'd56: w128_re = -16'sd3784;
      7'd57: w128_re = -16'sd3857;
      7'd58: w128_re = -16'sd3920;
      7'd59: w128_re = -16'sd3973;
      7'd60: w128_re = -16'sd4017;
      7'd61: w128_re = -16'sd4052;
      7'd62: w128_re = -16'sd4076;
      7'd63: w128_re = -16'sd4091;
      7'd64: w128_re = -16'sd4096;
      7'd65: w128_re = -16'sd4091;
      7'd66: w128_re = -16'sd4076;
      7'd67: w128_re = -16'sd4052;
      7'd68: w128_re = -16'sd4017;
      7'd69: w128_re = -16'sd3973;
      7'd70: w128_re = -16'sd3920;
      7'd71: w128_re = -16'sd3857;
      7'd72: w128_re = -16'sd3784;
      7'd73: w128_re = -16'sd3703;
      7'd74: w128_re = -16'sd3612;
      7'd75: w128_re = -16'sd3513;
      7'd76: w128_re = -16'sd3406;
      7'd77: w128_re = -16'sd3290;
      7'd78: w128_re = -16'sd3166;
      7'd79: w128_re = -16'sd3035;
      7'd80: w128_re = -16'sd2896;
      7'd81: w128_re = -16'sd2751;
      7'd82: w128_re = -16'sd2598;
      7'd83: w128_re = -16'sd2440;
      7'd84: w128_re = -16'sd2276;
      7'd85: w128_re = -16'sd2106;
      7'd86: w128_re = -16'sd1931;
      7'd87: w128_re = -16'sd1751;
      7'd88: w128_re = -16'sd1567;
      7'd89: w128_re = -16'sd1380;
      7'd90: w128_re = -16'sd1189;
      7'd91: w128_re = -16'sd995;
      7'd92: w128_re = -16'sd799;
      7'd93: w128_re = -16'sd601;
      7'd94: w128_re = -16'sd401;
      7'd95: w128_re = -16'sd201;
      7'd96: w128_re = 16'sd0;
      7'd97: w128_re = 16'sd201;
      7'd98: w128_re = 16'sd401;
      7'd99: w128_re = 16'sd601;
      7'd100: w128_re = 16'sd799;
      7'd101: w128_re = 16'sd995;
      7'd102: w128_re = 16'sd1189;
      7'd103: w128_re = 16'sd1380;
      7'd104: w128_re = 16'sd1567;
      7'd105: w128_re = 16'sd1751;
      7'd106: w128_re = 16'sd1931;
      7'd107: w128_re = 16'sd2106;
      7'd108: w128_re = 16'sd2276;
      7'd109: w128_re = 16'sd2440;
      7'd110: w128_re = 16'sd2598;
      7'd111: w128_re = 16'sd2751;
      7'd112: w128_re = 16'sd2896;
      7'd113: w128_re = 16'sd3035;
      7'd114: w128_re = 16'sd3166;
      7'd115: w128_re = 16'sd3290;
      7'd116: w128_re = 16'sd3406;
      7'd117: w128_re = 16'sd3513;
      7'd118: w128_re = 16'sd3612;
      7'd119: w128_re = 16'sd3703;
      7'd120: w128_re = 16'sd3784;
      7'd121: w128_re = 16'sd3857;
      7'd122: w128_re = 16'sd3920;
      7'd123: w128_re = 16'sd3973;
      7'd124: w128_re = 16'sd4017;
      7'd125: w128_re = 16'sd4052;
      7'd126: w128_re = 16'sd4076;
      7'd127: w128_re = 16'sd4091;
      default: w128_re = 16'sd0;
    endcase
  endfunction

  function signed [15:0] w128_im;
    input [6:0] idx;
    case (idx)
      7'd0: w128_im = 16'sd0;
      7'd1: w128_im = 16'sd201;
      7'd2: w128_im = 16'sd401;
      7'd3: w128_im = 16'sd601;
      7'd4: w128_im = 16'sd799;
      7'd5: w128_im = 16'sd995;
      7'd6: w128_im = 16'sd1189;
      7'd7: w128_im = 16'sd1380;
      7'd8: w128_im = 16'sd1567;
      7'd9: w128_im = 16'sd1751;
      7'd10: w128_im = 16'sd1931;
      7'd11: w128_im = 16'sd2106;
      7'd12: w128_im = 16'sd2276;
      7'd13: w128_im = 16'sd2440;
      7'd14: w128_im = 16'sd2598;
      7'd15: w128_im = 16'sd2751;
      7'd16: w128_im = 16'sd2896;
      7'd17: w128_im = 16'sd3035;
      7'd18: w128_im = 16'sd3166;
      7'd19: w128_im = 16'sd3290;
      7'd20: w128_im = 16'sd3406;
      7'd21: w128_im = 16'sd3513;
      7'd22: w128_im = 16'sd3612;
      7'd23: w128_im = 16'sd3703;
      7'd24: w128_im = 16'sd3784;
      7'd25: w128_im = 16'sd3857;
      7'd26: w128_im = 16'sd3920;
      7'd27: w128_im = 16'sd3973;
      7'd28: w128_im = 16'sd4017;
      7'd29: w128_im = 16'sd4052;
      7'd30: w128_im = 16'sd4076;
      7'd31: w128_im = 16'sd4091;
      7'd32: w128_im = 16'sd4096;
      7'd33: w128_im = 16'sd4091;
      7'd34: w128_im = 16'sd4076;
      7'd35: w128_im = 16'sd4052;
      7'd36: w128_im = 16'sd4017;
      7'd37: w128_im = 16'sd3973;
      7'd38: w128_im = 16'sd3920;
      7'd39: w128_im = 16'sd3857;
      7'd40: w128_im = 16'sd3784;
      7'd41: w128_im = 16'sd3703;
      7'd42: w128_im = 16'sd3612;
      7'd43: w128_im = 16'sd3513;
      7'd44: w128_im = 16'sd3406;
      7'd45: w128_im = 16'sd3290;
      7'd46: w128_im = 16'sd3166;
      7'd47: w128_im = 16'sd3035;
      7'd48: w128_im = 16'sd2896;
      7'd49: w128_im = 16'sd2751;
      7'd50: w128_im = 16'sd2598;
      7'd51: w128_im = 16'sd2440;
      7'd52: w128_im = 16'sd2276;
      7'd53: w128_im = 16'sd2106;
      7'd54: w128_im = 16'sd1931;
      7'd55: w128_im = 16'sd1751;
      7'd56: w128_im = 16'sd1567;
      7'd57: w128_im = 16'sd1380;
      7'd58: w128_im = 16'sd1189;
      7'd59: w128_im = 16'sd995;
      7'd60: w128_im = 16'sd799;
      7'd61: w128_im = 16'sd601;
      7'd62: w128_im = 16'sd401;
      7'd63: w128_im = 16'sd201;
      7'd64: w128_im = 16'sd0;
      7'd65: w128_im = -16'sd201;
      7'd66: w128_im = -16'sd401;
      7'd67: w128_im = -16'sd601;
      7'd68: w128_im = -16'sd799;
      7'd69: w128_im = -16'sd995;
      7'd70: w128_im = -16'sd1189;
      7'd71: w128_im = -16'sd1380;
      7'd72: w128_im = -16'sd1567;
      7'd73: w128_im = -16'sd1751;
      7'd74: w128_im = -16'sd1931;
      7'd75: w128_im = -16'sd2106;
      7'd76: w128_im = -16'sd2276;
      7'd77: w128_im = -16'sd2440;
      7'd78: w128_im = -16'sd2598;
      7'd79: w128_im = -16'sd2751;
      7'd80: w128_im = -16'sd2896;
      7'd81: w128_im = -16'sd3035;
      7'd82: w128_im = -16'sd3166;
      7'd83: w128_im = -16'sd3290;
      7'd84: w128_im = -16'sd3406;
      7'd85: w128_im = -16'sd3513;
      7'd86: w128_im = -16'sd3612;
      7'd87: w128_im = -16'sd3703;
      7'd88: w128_im = -16'sd3784;
      7'd89: w128_im = -16'sd3857;
      7'd90: w128_im = -16'sd3920;
      7'd91: w128_im = -16'sd3973;
      7'd92: w128_im = -16'sd4017;
      7'd93: w128_im = -16'sd4052;
      7'd94: w128_im = -16'sd4076;
      7'd95: w128_im = -16'sd4091;
      7'd96: w128_im = -16'sd4096;
      7'd97: w128_im = -16'sd4091;
      7'd98: w128_im = -16'sd4076;
      7'd99: w128_im = -16'sd4052;
      7'd100: w128_im = -16'sd4017;
      7'd101: w128_im = -16'sd3973;
      7'd102: w128_im = -16'sd3920;
      7'd103: w128_im = -16'sd3857;
      7'd104: w128_im = -16'sd3784;
      7'd105: w128_im = -16'sd3703;
      7'd106: w128_im = -16'sd3612;
      7'd107: w128_im = -16'sd3513;
      7'd108: w128_im = -16'sd3406;
      7'd109: w128_im = -16'sd3290;
      7'd110: w128_im = -16'sd3166;
      7'd111: w128_im = -16'sd3035;
      7'd112: w128_im = -16'sd2896;
      7'd113: w128_im = -16'sd2751;
      7'd114: w128_im = -16'sd2598;
      7'd115: w128_im = -16'sd2440;
      7'd116: w128_im = -16'sd2276;
      7'd117: w128_im = -16'sd2106;
      7'd118: w128_im = -16'sd1931;
      7'd119: w128_im = -16'sd1751;
      7'd120: w128_im = -16'sd1567;
      7'd121: w128_im = -16'sd1380;
      7'd122: w128_im = -16'sd1189;
      7'd123: w128_im = -16'sd995;
      7'd124: w128_im = -16'sd799;
      7'd125: w128_im = -16'sd601;
      7'd126: w128_im = -16'sd401;
      7'd127: w128_im = -16'sd201;
      default: w128_im = 16'sd0;
    endcase
  endfunction

  // ── Combinational IFFT MAC for the current output sample ────────────────
  // out_cnt encodes: sample = out_cnt>>1, half = out_cnt[0] (0=I, 1=Q).
  reg  [7:0]  sample_idx;       // 0..136
  reg  [6:0]  tau;              // time index into the 128-pt IFFT
  reg  [6:0]  w_idx;
  reg signed [63:0] acc_re, acc_im;
  reg signed [63:0] pr_re, pr_im;
  reg signed [63:0] shifted;

  always @(*) begin
    sample_idx = out_cnt[8:1];
    tau = (sample_idx < 9) ? (sample_idx + 119) : (sample_idx - 9);
    acc_re = 64'sd0;
    acc_im = 64'sd0;
    for (cj = 0; cj < 12; cj = cj + 1) begin
      w_idx = (((58 + cj) * tau) & 7'h7f);
      // complex multiply: spread[cj] * W128[w_idx]
      pr_re = spread_re[cj] * w128_re(w_idx) - spread_im[cj] * w128_im(w_idx);
      pr_im = spread_re[cj] * w128_im(w_idx) + spread_im[cj] * w128_re(w_idx);
      acc_re = acc_re + pr_re;
      acc_im = acc_im + pr_im;
    end
    // round-shift then saturate to int8 for the selected half (I or Q)
    if (out_cnt[0] == 1'b0)
      shifted = (acc_re + (64'sd1 <<< (31 - 1))) >>> 31;
    else
      shifted = (acc_im + (64'sd1 <<< (31 - 1))) >>> 31;
  end

  wire signed [7:0] out_byte =
      (shifted >  64'sd127)  ?  8'sd127 :
      (shifted < -64'sd128)  ? -8'sd128 :
      shifted[7:0];

  // ── Main sequential FSM ─────────────────────────────────────────────────
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state      <= S_IDLE;
      load_cnt   <= 5'd0;
      out_cnt    <= 9'd0;
      dout       <= 8'd0;
      dout_valid <= 1'b0;
      busy       <= 1'b0;
      done       <= 1'b0;
    end else begin
      done       <= 1'b0;
      dout_valid <= 1'b0;

      case (state)
        S_IDLE: begin
          busy <= 1'b0;
          if (din_valid) begin
            buf[0]   <= din;        // capture first byte at the transition
            load_cnt <= 5'd1;
            busy     <= 1'b1;
            state    <= S_LOAD;
          end
        end

        S_LOAD: begin
          busy <= 1'b1;
          buf[load_cnt] <= din;
          if (load_cnt == 5'd23) begin
            load_cnt <= 5'd0;
            state    <= S_DFT;
          end else begin
            load_cnt <= load_cnt + 5'd1;
          end
        end

        S_DFT: begin
          // The dedicated DFT always-block (below) fills spread_* this cycle;
          // results are ready by the time we are in S_STREAM next cycle.
          busy    <= 1'b1;
          state   <= S_STREAM;
          out_cnt <= 9'd0;
        end

        S_STREAM: begin
          busy       <= 1'b1;
          dout       <= out_byte;
          dout_valid <= 1'b1;
          if (out_cnt == 9'd273) begin
            state <= S_IDLE;
            done  <= 1'b1;
          end else begin
            out_cnt <= out_cnt + 9'd1;
          end
        end

        default: state <= S_IDLE;
      endcase
    end
  end

  // ── DFT computation (separate always to use a clean accumulator loop) ────
  // Triggered the cycle we enter S_DFT; results are ready for S_STREAM.
  reg signed [31:0] dacc_re, dacc_im;
  reg signed [31:0] dpr_re,  dpr_im;
  reg [3:0] d12;
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      for (dj = 0; dj < 12; dj = dj + 1) begin
        spread_re[dj] <= 32'sd0;
        spread_im[dj] <= 32'sd0;
      end
    end else if (state == S_DFT) begin
      for (dj = 0; dj < 12; dj = dj + 1) begin
        dacc_re = 32'sd0;
        dacc_im = 32'sd0;
        for (dn = 0; dn < 12; dn = dn + 1) begin
          d12 = ((dn * dj) % 12);
          dpr_re = buf[2*dn] * w12_re(d12) - buf[2*dn+1] * w12_im(d12);
          dpr_im = buf[2*dn] * w12_im(d12) + buf[2*dn+1] * w12_re(d12);
          dacc_re = dacc_re + dpr_re;
          dacc_im = dacc_im + dpr_im;
        end
        spread_re[dj] <= dacc_re;
        spread_im[dj] <= dacc_im;
      end
    end
  end

endmodule
