// butterfold_kernel.v  —  GENERATED by gen_reference.py.  BIT-EXACT. DO NOT HAND-EDIT.
//
// The precision-critical datapath of ButterFold: the two integer twiddle ROMs
// (W12 forward DFT, W128 inverse FFT), the single shared complex multiplier,
// and the round-shift+saturate to int8. Self-validated against butterfold_sim
// (Stage-6 seed-42 golden-model EVM < 2%). The agentic wrapper INSTANTIATES this
// module but must not modify it — one wrong twiddle entry breaks the EVM floor.
//
// Frozen params: K=12, M=128, CP=9, START=58, A=B=9, SHIFT=25

`timescale 1ns/1ps
module butterfold_kernel (
  input  wire signed [23:0] a_re,    // operand A real (inbuf byte or spread bin)
  input  wire signed [23:0] a_im,    // operand A imag
  input  wire        use_ifft,                 // 0 = DFT (W12 via idx12), 1 = IFFT (W128 via w_idx)
  input  wire [3:0]  dft_n,                    // DFT inner index (for idx12 LUT)
  input  wire [3:0]  dft_j,                    // DFT outer index (for idx12 LUT)
  input  wire [6:0]  w_idx,                    // IFFT twiddle index ((START+j)*tau) mod 128
  output wire signed [39:0] prod_re,    // complex product a * W (real)
  output wire signed [39:0] prod_im,    // complex product a * W (imag)
  input  wire signed [39:0] sum_re,     // full accumulated sum (real) to round
  input  wire signed [39:0] sum_im,     // full accumulated sum (imag) to round
  output wire signed [7:0] byte_re,            // round-shift+saturate(sum_re) -> int8
  output wire signed [7:0] byte_im             // round-shift+saturate(sum_im) -> int8
);

  // ── Twiddle ROMs + (n*j) mod 12 LUT (combinational, synthesizable) ──────
  function signed [11:0] w12_re;
    input [3:0] idx;
    case (idx)
      4'd0: w12_re = 12'sd512;
      4'd1: w12_re = 12'sd443;
      4'd2: w12_re = 12'sd256;
      4'd3: w12_re = 12'sd0;
      4'd4: w12_re = -12'sd256;
      4'd5: w12_re = -12'sd443;
      4'd6: w12_re = -12'sd512;
      4'd7: w12_re = -12'sd443;
      4'd8: w12_re = -12'sd256;
      4'd9: w12_re = 12'sd0;
      4'd10: w12_re = 12'sd256;
      4'd11: w12_re = 12'sd443;
      default: w12_re = 12'sd0;
    endcase
  endfunction

  function signed [11:0] w12_im;
    input [3:0] idx;
    case (idx)
      4'd0: w12_im = 12'sd0;
      4'd1: w12_im = -12'sd256;
      4'd2: w12_im = -12'sd443;
      4'd3: w12_im = -12'sd512;
      4'd4: w12_im = -12'sd443;
      4'd5: w12_im = -12'sd256;
      4'd6: w12_im = 12'sd0;
      4'd7: w12_im = 12'sd256;
      4'd8: w12_im = 12'sd443;
      4'd9: w12_im = 12'sd512;
      4'd10: w12_im = 12'sd443;
      4'd11: w12_im = 12'sd256;
      default: w12_im = 12'sd0;
    endcase
  endfunction

  function signed [11:0] w128_re;
    input [6:0] idx;
    case (idx)
      7'd0: w128_re = 12'sd512;
      7'd1: w128_re = 12'sd511;
      7'd2: w128_re = 12'sd510;
      7'd3: w128_re = 12'sd506;
      7'd4: w128_re = 12'sd502;
      7'd5: w128_re = 12'sd497;
      7'd6: w128_re = 12'sd490;
      7'd7: w128_re = 12'sd482;
      7'd8: w128_re = 12'sd473;
      7'd9: w128_re = 12'sd463;
      7'd10: w128_re = 12'sd452;
      7'd11: w128_re = 12'sd439;
      7'd12: w128_re = 12'sd426;
      7'd13: w128_re = 12'sd411;
      7'd14: w128_re = 12'sd396;
      7'd15: w128_re = 12'sd379;
      7'd16: w128_re = 12'sd362;
      7'd17: w128_re = 12'sd344;
      7'd18: w128_re = 12'sd325;
      7'd19: w128_re = 12'sd305;
      7'd20: w128_re = 12'sd284;
      7'd21: w128_re = 12'sd263;
      7'd22: w128_re = 12'sd241;
      7'd23: w128_re = 12'sd219;
      7'd24: w128_re = 12'sd196;
      7'd25: w128_re = 12'sd172;
      7'd26: w128_re = 12'sd149;
      7'd27: w128_re = 12'sd124;
      7'd28: w128_re = 12'sd100;
      7'd29: w128_re = 12'sd75;
      7'd30: w128_re = 12'sd50;
      7'd31: w128_re = 12'sd25;
      7'd32: w128_re = 12'sd0;
      7'd33: w128_re = -12'sd25;
      7'd34: w128_re = -12'sd50;
      7'd35: w128_re = -12'sd75;
      7'd36: w128_re = -12'sd100;
      7'd37: w128_re = -12'sd124;
      7'd38: w128_re = -12'sd149;
      7'd39: w128_re = -12'sd172;
      7'd40: w128_re = -12'sd196;
      7'd41: w128_re = -12'sd219;
      7'd42: w128_re = -12'sd241;
      7'd43: w128_re = -12'sd263;
      7'd44: w128_re = -12'sd284;
      7'd45: w128_re = -12'sd305;
      7'd46: w128_re = -12'sd325;
      7'd47: w128_re = -12'sd344;
      7'd48: w128_re = -12'sd362;
      7'd49: w128_re = -12'sd379;
      7'd50: w128_re = -12'sd396;
      7'd51: w128_re = -12'sd411;
      7'd52: w128_re = -12'sd426;
      7'd53: w128_re = -12'sd439;
      7'd54: w128_re = -12'sd452;
      7'd55: w128_re = -12'sd463;
      7'd56: w128_re = -12'sd473;
      7'd57: w128_re = -12'sd482;
      7'd58: w128_re = -12'sd490;
      7'd59: w128_re = -12'sd497;
      7'd60: w128_re = -12'sd502;
      7'd61: w128_re = -12'sd506;
      7'd62: w128_re = -12'sd510;
      7'd63: w128_re = -12'sd511;
      7'd64: w128_re = -12'sd512;
      7'd65: w128_re = -12'sd511;
      7'd66: w128_re = -12'sd510;
      7'd67: w128_re = -12'sd506;
      7'd68: w128_re = -12'sd502;
      7'd69: w128_re = -12'sd497;
      7'd70: w128_re = -12'sd490;
      7'd71: w128_re = -12'sd482;
      7'd72: w128_re = -12'sd473;
      7'd73: w128_re = -12'sd463;
      7'd74: w128_re = -12'sd452;
      7'd75: w128_re = -12'sd439;
      7'd76: w128_re = -12'sd426;
      7'd77: w128_re = -12'sd411;
      7'd78: w128_re = -12'sd396;
      7'd79: w128_re = -12'sd379;
      7'd80: w128_re = -12'sd362;
      7'd81: w128_re = -12'sd344;
      7'd82: w128_re = -12'sd325;
      7'd83: w128_re = -12'sd305;
      7'd84: w128_re = -12'sd284;
      7'd85: w128_re = -12'sd263;
      7'd86: w128_re = -12'sd241;
      7'd87: w128_re = -12'sd219;
      7'd88: w128_re = -12'sd196;
      7'd89: w128_re = -12'sd172;
      7'd90: w128_re = -12'sd149;
      7'd91: w128_re = -12'sd124;
      7'd92: w128_re = -12'sd100;
      7'd93: w128_re = -12'sd75;
      7'd94: w128_re = -12'sd50;
      7'd95: w128_re = -12'sd25;
      7'd96: w128_re = 12'sd0;
      7'd97: w128_re = 12'sd25;
      7'd98: w128_re = 12'sd50;
      7'd99: w128_re = 12'sd75;
      7'd100: w128_re = 12'sd100;
      7'd101: w128_re = 12'sd124;
      7'd102: w128_re = 12'sd149;
      7'd103: w128_re = 12'sd172;
      7'd104: w128_re = 12'sd196;
      7'd105: w128_re = 12'sd219;
      7'd106: w128_re = 12'sd241;
      7'd107: w128_re = 12'sd263;
      7'd108: w128_re = 12'sd284;
      7'd109: w128_re = 12'sd305;
      7'd110: w128_re = 12'sd325;
      7'd111: w128_re = 12'sd344;
      7'd112: w128_re = 12'sd362;
      7'd113: w128_re = 12'sd379;
      7'd114: w128_re = 12'sd396;
      7'd115: w128_re = 12'sd411;
      7'd116: w128_re = 12'sd426;
      7'd117: w128_re = 12'sd439;
      7'd118: w128_re = 12'sd452;
      7'd119: w128_re = 12'sd463;
      7'd120: w128_re = 12'sd473;
      7'd121: w128_re = 12'sd482;
      7'd122: w128_re = 12'sd490;
      7'd123: w128_re = 12'sd497;
      7'd124: w128_re = 12'sd502;
      7'd125: w128_re = 12'sd506;
      7'd126: w128_re = 12'sd510;
      7'd127: w128_re = 12'sd511;
      default: w128_re = 12'sd0;
    endcase
  endfunction

  function signed [11:0] w128_im;
    input [6:0] idx;
    case (idx)
      7'd0: w128_im = 12'sd0;
      7'd1: w128_im = 12'sd25;
      7'd2: w128_im = 12'sd50;
      7'd3: w128_im = 12'sd75;
      7'd4: w128_im = 12'sd100;
      7'd5: w128_im = 12'sd124;
      7'd6: w128_im = 12'sd149;
      7'd7: w128_im = 12'sd172;
      7'd8: w128_im = 12'sd196;
      7'd9: w128_im = 12'sd219;
      7'd10: w128_im = 12'sd241;
      7'd11: w128_im = 12'sd263;
      7'd12: w128_im = 12'sd284;
      7'd13: w128_im = 12'sd305;
      7'd14: w128_im = 12'sd325;
      7'd15: w128_im = 12'sd344;
      7'd16: w128_im = 12'sd362;
      7'd17: w128_im = 12'sd379;
      7'd18: w128_im = 12'sd396;
      7'd19: w128_im = 12'sd411;
      7'd20: w128_im = 12'sd426;
      7'd21: w128_im = 12'sd439;
      7'd22: w128_im = 12'sd452;
      7'd23: w128_im = 12'sd463;
      7'd24: w128_im = 12'sd473;
      7'd25: w128_im = 12'sd482;
      7'd26: w128_im = 12'sd490;
      7'd27: w128_im = 12'sd497;
      7'd28: w128_im = 12'sd502;
      7'd29: w128_im = 12'sd506;
      7'd30: w128_im = 12'sd510;
      7'd31: w128_im = 12'sd511;
      7'd32: w128_im = 12'sd512;
      7'd33: w128_im = 12'sd511;
      7'd34: w128_im = 12'sd510;
      7'd35: w128_im = 12'sd506;
      7'd36: w128_im = 12'sd502;
      7'd37: w128_im = 12'sd497;
      7'd38: w128_im = 12'sd490;
      7'd39: w128_im = 12'sd482;
      7'd40: w128_im = 12'sd473;
      7'd41: w128_im = 12'sd463;
      7'd42: w128_im = 12'sd452;
      7'd43: w128_im = 12'sd439;
      7'd44: w128_im = 12'sd426;
      7'd45: w128_im = 12'sd411;
      7'd46: w128_im = 12'sd396;
      7'd47: w128_im = 12'sd379;
      7'd48: w128_im = 12'sd362;
      7'd49: w128_im = 12'sd344;
      7'd50: w128_im = 12'sd325;
      7'd51: w128_im = 12'sd305;
      7'd52: w128_im = 12'sd284;
      7'd53: w128_im = 12'sd263;
      7'd54: w128_im = 12'sd241;
      7'd55: w128_im = 12'sd219;
      7'd56: w128_im = 12'sd196;
      7'd57: w128_im = 12'sd172;
      7'd58: w128_im = 12'sd149;
      7'd59: w128_im = 12'sd124;
      7'd60: w128_im = 12'sd100;
      7'd61: w128_im = 12'sd75;
      7'd62: w128_im = 12'sd50;
      7'd63: w128_im = 12'sd25;
      7'd64: w128_im = 12'sd0;
      7'd65: w128_im = -12'sd25;
      7'd66: w128_im = -12'sd50;
      7'd67: w128_im = -12'sd75;
      7'd68: w128_im = -12'sd100;
      7'd69: w128_im = -12'sd124;
      7'd70: w128_im = -12'sd149;
      7'd71: w128_im = -12'sd172;
      7'd72: w128_im = -12'sd196;
      7'd73: w128_im = -12'sd219;
      7'd74: w128_im = -12'sd241;
      7'd75: w128_im = -12'sd263;
      7'd76: w128_im = -12'sd284;
      7'd77: w128_im = -12'sd305;
      7'd78: w128_im = -12'sd325;
      7'd79: w128_im = -12'sd344;
      7'd80: w128_im = -12'sd362;
      7'd81: w128_im = -12'sd379;
      7'd82: w128_im = -12'sd396;
      7'd83: w128_im = -12'sd411;
      7'd84: w128_im = -12'sd426;
      7'd85: w128_im = -12'sd439;
      7'd86: w128_im = -12'sd452;
      7'd87: w128_im = -12'sd463;
      7'd88: w128_im = -12'sd473;
      7'd89: w128_im = -12'sd482;
      7'd90: w128_im = -12'sd490;
      7'd91: w128_im = -12'sd497;
      7'd92: w128_im = -12'sd502;
      7'd93: w128_im = -12'sd506;
      7'd94: w128_im = -12'sd510;
      7'd95: w128_im = -12'sd511;
      7'd96: w128_im = -12'sd512;
      7'd97: w128_im = -12'sd511;
      7'd98: w128_im = -12'sd510;
      7'd99: w128_im = -12'sd506;
      7'd100: w128_im = -12'sd502;
      7'd101: w128_im = -12'sd497;
      7'd102: w128_im = -12'sd490;
      7'd103: w128_im = -12'sd482;
      7'd104: w128_im = -12'sd473;
      7'd105: w128_im = -12'sd463;
      7'd106: w128_im = -12'sd452;
      7'd107: w128_im = -12'sd439;
      7'd108: w128_im = -12'sd426;
      7'd109: w128_im = -12'sd411;
      7'd110: w128_im = -12'sd396;
      7'd111: w128_im = -12'sd379;
      7'd112: w128_im = -12'sd362;
      7'd113: w128_im = -12'sd344;
      7'd114: w128_im = -12'sd325;
      7'd115: w128_im = -12'sd305;
      7'd116: w128_im = -12'sd284;
      7'd117: w128_im = -12'sd263;
      7'd118: w128_im = -12'sd241;
      7'd119: w128_im = -12'sd219;
      7'd120: w128_im = -12'sd196;
      7'd121: w128_im = -12'sd172;
      7'd122: w128_im = -12'sd149;
      7'd123: w128_im = -12'sd124;
      7'd124: w128_im = -12'sd100;
      7'd125: w128_im = -12'sd75;
      7'd126: w128_im = -12'sd50;
      7'd127: w128_im = -12'sd25;
      default: w128_im = 12'sd0;
    endcase
  endfunction

  function [3:0] idx12;
    input [3:0] nn;
    input [3:0] jj;
    case ({nn, jj})
      8'h00: idx12 = 4'd0;
      8'h01: idx12 = 4'd0;
      8'h02: idx12 = 4'd0;
      8'h03: idx12 = 4'd0;
      8'h04: idx12 = 4'd0;
      8'h05: idx12 = 4'd0;
      8'h06: idx12 = 4'd0;
      8'h07: idx12 = 4'd0;
      8'h08: idx12 = 4'd0;
      8'h09: idx12 = 4'd0;
      8'h0a: idx12 = 4'd0;
      8'h0b: idx12 = 4'd0;
      8'h10: idx12 = 4'd0;
      8'h11: idx12 = 4'd1;
      8'h12: idx12 = 4'd2;
      8'h13: idx12 = 4'd3;
      8'h14: idx12 = 4'd4;
      8'h15: idx12 = 4'd5;
      8'h16: idx12 = 4'd6;
      8'h17: idx12 = 4'd7;
      8'h18: idx12 = 4'd8;
      8'h19: idx12 = 4'd9;
      8'h1a: idx12 = 4'd10;
      8'h1b: idx12 = 4'd11;
      8'h20: idx12 = 4'd0;
      8'h21: idx12 = 4'd2;
      8'h22: idx12 = 4'd4;
      8'h23: idx12 = 4'd6;
      8'h24: idx12 = 4'd8;
      8'h25: idx12 = 4'd10;
      8'h26: idx12 = 4'd0;
      8'h27: idx12 = 4'd2;
      8'h28: idx12 = 4'd4;
      8'h29: idx12 = 4'd6;
      8'h2a: idx12 = 4'd8;
      8'h2b: idx12 = 4'd10;
      8'h30: idx12 = 4'd0;
      8'h31: idx12 = 4'd3;
      8'h32: idx12 = 4'd6;
      8'h33: idx12 = 4'd9;
      8'h34: idx12 = 4'd0;
      8'h35: idx12 = 4'd3;
      8'h36: idx12 = 4'd6;
      8'h37: idx12 = 4'd9;
      8'h38: idx12 = 4'd0;
      8'h39: idx12 = 4'd3;
      8'h3a: idx12 = 4'd6;
      8'h3b: idx12 = 4'd9;
      8'h40: idx12 = 4'd0;
      8'h41: idx12 = 4'd4;
      8'h42: idx12 = 4'd8;
      8'h43: idx12 = 4'd0;
      8'h44: idx12 = 4'd4;
      8'h45: idx12 = 4'd8;
      8'h46: idx12 = 4'd0;
      8'h47: idx12 = 4'd4;
      8'h48: idx12 = 4'd8;
      8'h49: idx12 = 4'd0;
      8'h4a: idx12 = 4'd4;
      8'h4b: idx12 = 4'd8;
      8'h50: idx12 = 4'd0;
      8'h51: idx12 = 4'd5;
      8'h52: idx12 = 4'd10;
      8'h53: idx12 = 4'd3;
      8'h54: idx12 = 4'd8;
      8'h55: idx12 = 4'd1;
      8'h56: idx12 = 4'd6;
      8'h57: idx12 = 4'd11;
      8'h58: idx12 = 4'd4;
      8'h59: idx12 = 4'd9;
      8'h5a: idx12 = 4'd2;
      8'h5b: idx12 = 4'd7;
      8'h60: idx12 = 4'd0;
      8'h61: idx12 = 4'd6;
      8'h62: idx12 = 4'd0;
      8'h63: idx12 = 4'd6;
      8'h64: idx12 = 4'd0;
      8'h65: idx12 = 4'd6;
      8'h66: idx12 = 4'd0;
      8'h67: idx12 = 4'd6;
      8'h68: idx12 = 4'd0;
      8'h69: idx12 = 4'd6;
      8'h6a: idx12 = 4'd0;
      8'h6b: idx12 = 4'd6;
      8'h70: idx12 = 4'd0;
      8'h71: idx12 = 4'd7;
      8'h72: idx12 = 4'd2;
      8'h73: idx12 = 4'd9;
      8'h74: idx12 = 4'd4;
      8'h75: idx12 = 4'd11;
      8'h76: idx12 = 4'd6;
      8'h77: idx12 = 4'd1;
      8'h78: idx12 = 4'd8;
      8'h79: idx12 = 4'd3;
      8'h7a: idx12 = 4'd10;
      8'h7b: idx12 = 4'd5;
      8'h80: idx12 = 4'd0;
      8'h81: idx12 = 4'd8;
      8'h82: idx12 = 4'd4;
      8'h83: idx12 = 4'd0;
      8'h84: idx12 = 4'd8;
      8'h85: idx12 = 4'd4;
      8'h86: idx12 = 4'd0;
      8'h87: idx12 = 4'd8;
      8'h88: idx12 = 4'd4;
      8'h89: idx12 = 4'd0;
      8'h8a: idx12 = 4'd8;
      8'h8b: idx12 = 4'd4;
      8'h90: idx12 = 4'd0;
      8'h91: idx12 = 4'd9;
      8'h92: idx12 = 4'd6;
      8'h93: idx12 = 4'd3;
      8'h94: idx12 = 4'd0;
      8'h95: idx12 = 4'd9;
      8'h96: idx12 = 4'd6;
      8'h97: idx12 = 4'd3;
      8'h98: idx12 = 4'd0;
      8'h99: idx12 = 4'd9;
      8'h9a: idx12 = 4'd6;
      8'h9b: idx12 = 4'd3;
      8'ha0: idx12 = 4'd0;
      8'ha1: idx12 = 4'd10;
      8'ha2: idx12 = 4'd8;
      8'ha3: idx12 = 4'd6;
      8'ha4: idx12 = 4'd4;
      8'ha5: idx12 = 4'd2;
      8'ha6: idx12 = 4'd0;
      8'ha7: idx12 = 4'd10;
      8'ha8: idx12 = 4'd8;
      8'ha9: idx12 = 4'd6;
      8'haa: idx12 = 4'd4;
      8'hab: idx12 = 4'd2;
      8'hb0: idx12 = 4'd0;
      8'hb1: idx12 = 4'd11;
      8'hb2: idx12 = 4'd10;
      8'hb3: idx12 = 4'd9;
      8'hb4: idx12 = 4'd8;
      8'hb5: idx12 = 4'd7;
      8'hb6: idx12 = 4'd6;
      8'hb7: idx12 = 4'd5;
      8'hb8: idx12 = 4'd4;
      8'hb9: idx12 = 4'd3;
      8'hba: idx12 = 4'd2;
      8'hbb: idx12 = 4'd1;
      default: idx12 = 4'd0;
    endcase
  endfunction

  // ── Twiddle selection: DFT uses W12[idx12(n,j)], IFFT uses W128[w_idx] ───
  wire [3:0] d12 = idx12(dft_n, dft_j);
  wire signed [11:0] b_re = use_ifft ? w128_re(w_idx) : w12_re(d12);
  wire signed [11:0] b_im = use_ifft ? w128_im(w_idx) : w12_im(d12);

  // ── The single complex multiplier (4 real multiplies) ───────────────────
  assign prod_re = a_re * b_re - a_im * b_im;
  assign prod_im = a_re * b_im + a_im * b_re;

  // ── Round-shift + saturate to int8 (final IFFT term) ────────────────────
  wire signed [39:0] shr_re = (sum_re + (40'sd1 <<< (25 - 1))) >>> 25;
  wire signed [39:0] shr_im = (sum_im + (40'sd1 <<< (25 - 1))) >>> 25;
  assign byte_re =
      (shr_re >  40'sd127) ?  8'sd127 : (shr_re < -40'sd128) ? -8'sd128 : shr_re[7:0];
  assign byte_im =
      (shr_im >  40'sd127) ?  8'sd127 : (shr_im < -40'sd128) ? -8'sd128 : shr_im[7:0];

endmodule
