// Auto-generated by LibreLane
module butterfold_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input rst_n,
  input clk,
  input[7:0] din,
  input din_valid_i,
  input dout_ready_i,
  output din_ready_o,
  output[7:0] dout,
  output dout_valid_o
);
endmodule
