/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module gf180mcu_fd_ip_sram__sram64x8m8wm1(CLK, CEN, GWEN, WEN, A, D, Q, VDD, VSS);
  input CLK;
  wire CLK;
  input CEN;
  wire CEN;
  input GWEN;
  wire GWEN;
  input [7:0] WEN;
  wire [7:0] WEN;
  input [5:0] A;
  wire [5:0] A;
  input [7:0] D;
  wire [7:0] D;
  output [7:0] Q;
  wire [7:0] Q;
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
endmodule
