create_clock -name core_clk -period 26.041667 [get_ports clk]
set_clock_uncertainty 0.0 [get_clocks core_clk]
set_input_delay 0.0 -clock core_clk [get_ports {din_valid_i din[*]}]
set_output_delay 0.0 -clock core_clk [get_ports {din_ready_o dout_valid_o dout[*]}]
set_case_analysis 1 [get_ports rst_n]
