#!/usr/bin/env python3
"""Generate the D03 ACH pin template DEF and RTL port glue from the
authoritative organizer interface spec.

Source of truth is D03.def/D03/project_defs/ACH/D03_ACH_interface.yaml, which
is supplied by the chipathon organizers and is NEVER edited here.  It names
135 project pins -- every pad control terminal included -- each with the
Metal2 rectangle(s) the block must present at its boundary.

The previous hand-made template carried only 23 pins and was labelled
"ACH_VALIDATION_ONLY / pad-control pins omitted", which combined with
FP_TEMPLATE_MATCH_MODE=permissive silently dropped every control pin.  That is
the defect behind the "digital I/O cells are missing control signals" review.

Both the yaml and the template DEF use 200 DBU/um, so translated_user
rectangles are copied verbatim with no scaling.
"""

from pathlib import Path
import json
import re

REPO = Path(__file__).resolve().parents[2]
SRC_YAML = REPO / "D03.def/D03/project_defs/ACH/D03_ACH_interface.yaml"
OUT_DEF = REPO / "butterfold_proto/physical/librelane/d03_ach_user_template.def"
OUT_JSON = REPO / "butterfold_proto/physical/d03_ach_ports.generated.json"

DBU_PER_UM = 200
DIE_DBU = (0, 0, 222000, 335000)          # 1110 x 1675 um

# Strapping for fixed unidirectional operation.  Identical to the values already
# proven in rtl/padframe/butterfold_padframe_top.sv and confirmed by the
# padframe LVS run (circuits match uniquely, 0 unmatched pins).
TIE = {"CS": 0, "SL": 0, "IE": 0, "OE": 1, "PU": 0, "PD": 0,
       "PDRV0": 1, "PDRV1": 1}


def parse_blocks(text):
    """Minimal targeted parser -- avoids a PyYAML dependency inside the flow."""
    out = []
    for blob in text.split("- user_pin_name:")[1:]:
        def scalar(key):
            m = re.search(rf"^\s*{key}:\s*(.+?)\s*$", blob, re.M)
            return m.group(1) if m else None

        rects = []
        for chunk in re.findall(
                r"translated_user:\s*\n((?:\s*-\s*-?\d+\s*\n){4})", blob):
            nums = [int(n) for n in re.findall(r"-?\d+", chunk)]
            if len(nums) == 4:
                rects.append(nums)
        out.append({
            "user_pin": blob.split("\n", 1)[0].strip(),
            "pin": scalar("project_pin"),
            "terminal": scalar("cell_terminal"),
            "direction": scalar("direction"),
            "use": scalar("use"),
            "slot": scalar("physical_pad_slot"),
            "rects": rects,
        })
    return out


def group_bus(names):
    """Collapse foo[0..N] into (foo, width); scalars come back width None."""
    buses, scalars = {}, []
    for n in names:
        m = re.match(r"^(.*)\[(\d+)\]$", n)
        if m:
            buses.setdefault(m.group(1), []).append(int(m.group(2)))
        else:
            scalars.append(n)
    return {b: max(i) + 1 for b, i in buses.items()}, scalars



OUT_SV = REPO / "butterfold_proto/rtl/top/butterfold_ach_top.sv"

# Core terminal A pin -> the butterfold_core output that drives it.
CORE_DRIVE = {"dout_OUT": "core_dout",
              "din_ready_o_OUT": "core_din_ready",
              "dout_valid_o_OUT": "core_dout_valid"}


def write_wrapper(blocks, ties):
    """Emit the ACH pin wrapper.  butterfold_core keeps the frozen design;
    this layer only presents the organizer interface and straps the pad
    controls for fixed unidirectional operation."""
    ins = [b["pin"] for b in blocks if b["direction"] == "INPUT"]
    outs = [b["pin"] for b in blocks if b["direction"] == "OUTPUT"]
    bus_in, scal_in = group_bus(ins)
    bus_out, scal_out = group_bus(outs)

    def decl(kind, name, width):
        rng = f"[{width - 1}:0] " if width else ""
        return f"    {kind} wire {rng}{name}"

    ports = []
    for n, w in sorted(bus_in.items()):
        ports.append(decl("input ", n, w))
    for n in sorted(scal_in):
        ports.append(decl("input ", n, None))
    for n, w in sorted(bus_out.items()):
        ports.append(decl("output", n, w))
    for n in sorted(scal_out):
        ports.append(decl("output", n, None))

    L = ["`timescale 1ns/1ps", "`default_nettype none", "",
         "// AUTO-GENERATED by gen_ach_interface.py -- do not hand-edit.",
         "// Presents the full 135-pin D03 ACH organizer interface.",
         "//",
         "// Per the organizer: every pad control pin must be driven by the",
         "// project block.  The padring instantiates the gf180mcu_fd_io cells;",
         "// this wrapper supplies their control terminals as constants for",
         "// fixed unidirectional operation, and passes data through to the",
         "// frozen butterfold_core.",
         "module butterfold_top #(",
         "    parameter integer TRANSACTION_FIFO_DEPTH = 1,",
         "    parameter integer TX_BYTE_INTERVAL = 1",
         ") (",
         ",\n".join(ports),
         "`ifdef USE_POWER_PINS",
         "    , inout wire VDD",
         "    , inout wire VSS",
         "`endif",
         ");",
         "",
         "    wire [7:0] core_dout;",
         "    wire       core_din_ready;",
         "    wire       core_dout_valid;",
         "",
         "    butterfold_core #(",
         "        .TRANSACTION_FIFO_DEPTH(TRANSACTION_FIFO_DEPTH),",
         "        .TX_BYTE_INTERVAL(TX_BYTE_INTERVAL)",
         "    ) u_core (",
         "        .rst_n(rst_n), .clk(clk), .din(din),",
         "        .din_valid_i(din_valid_i), .din_ready_o(core_din_ready),",
         "        .dout(core_dout), .dout_valid_o(core_dout_valid)",
         "`ifdef USE_POWER_PINS",
         "        , .VDD(VDD), .VSS(VSS)",
         "`endif",
         "    );",
         "",
         "    // Data path out to the pad A terminals.",
         ]
    for pin, sig in sorted(CORE_DRIVE.items()):
        L.append(f"    assign {pin:<18} = {sig};")

    L += ["",
          "    // Pad control strapping: CS=0 SL=0 IE=0 OE=1 PU=0 PD=0",
          "    // PDRV0=1 PDRV1=1 on outputs; PU=0 PD=0 on inputs.",
          ]
    emitted = set()
    for name, width in sorted(bus_out.items()):
        if name in CORE_DRIVE:
            continue
        term = name.split("_")[-1]
        v = ties.get(f"{name}[0]")
        if v is None:
            continue
        lit = f"{{{width}{{1'b{v}}}}}"
        L.append(f"    assign {name:<18} = {lit};")
        emitted.add(name)
    for name in sorted(scal_out):
        if name in CORE_DRIVE or name in emitted:
            continue
        v = ties.get(name)
        if v is None:
            continue
        L.append(f"    assign {name:<18} = 1'b{v};")

    L += ["", "endmodule", "", "`default_nettype wire", ""]
    OUT_SV.write_text("\n".join(L))
    print(f"wrote {OUT_SV.relative_to(REPO)}  "
          f"({len(ports)} ports + VDD/VSS)")


def main():
    blocks = parse_blocks(SRC_YAML.read_text())
    if len(blocks) != 135:
        raise SystemExit(f"expected 135 interface pins, parsed {len(blocks)}")

    missing = [b["pin"] for b in blocks if not b["rects"]]
    if missing:
        raise SystemExit(f"no translated_user rectangle for: {missing}")

    # ---- DEF template -------------------------------------------------
    lines = [
        "# AUTO-GENERATED by gen_ach_interface.py -- do not hand-edit.",
        f"# Source: {SRC_YAML.relative_to(REPO)}",
        "# Complete organizer interface: all 135 project pins including every",
        "# pad control terminal.  Supersedes the ACH_VALIDATION_ONLY template",
        "# that omitted them.",
        "VERSION 5.8 ;",
        'DIVIDERCHAR "/" ;',
        'BUSBITCHARS "[]" ;',
        "DESIGN butterfold_top ;",
        f"UNITS DISTANCE MICRONS {DBU_PER_UM} ;",
        f"DIEAREA ( {DIE_DBU[0]} {DIE_DBU[1]} ) ( {DIE_DBU[2]} {DIE_DBU[3]} ) ;",
        f"PINS {len(blocks)} ;",
    ]
    for b in blocks:
        use = {"POWER": "POWER", "GROUND": "GROUND"}.get(b["use"], "SIGNAL")
        if b["terminal"] == "DVDD":
            use = "POWER"
        elif b["terminal"] == "DVSS":
            use = "GROUND"
        head = (f"- {b['pin']} + NET {b['pin']} + DIRECTION {b['direction']}"
                f" + USE {use}")
        lines.append(head)
        # Every rectangle is emitted.  For VDD/VSS this is what connects the
        # supply to *all* padring slots rather than one, which is the fix the
        # integration team asked for on the M2 minimum-width errors.
        for x1, y1, x2, y2 in b["rects"]:
            lines.append(f"  + LAYER Metal2 ( {x1} {y1} ) ( {x2} {y2} )")
        lines.append("  + FIXED ( 0 0 ) N ;")
    lines.append("END PINS")
    lines.append("END DESIGN")
    OUT_DEF.write_text("\n".join(lines) + "\n")

    # ---- port model for the RTL step ----------------------------------
    ins = [b["pin"] for b in blocks if b["direction"] == "INPUT"]
    outs = [b["pin"] for b in blocks if b["direction"] == "OUTPUT"]
    inouts = [b["pin"] for b in blocks if b["direction"] == "INOUT"]
    ties = {b["pin"]: TIE[b["terminal"]]
            for b in blocks if b["terminal"] in TIE}
    data_out = {b["pin"]: b["user_pin"]
                for b in blocks if b["terminal"] == "A"}
    data_in = {b["pin"]: b["user_pin"]
               for b in blocks if b["terminal"] == "Y"}

    model = {
        "inputs": sorted(ins), "outputs": sorted(outs), "inouts": sorted(inouts),
        "tied_constants": ties, "core_driven": data_out, "pad_received": data_in,
        "bus_inputs": group_bus(ins)[0], "bus_outputs": group_bus(outs)[0],
    }
    OUT_JSON.write_text(json.dumps(model, indent=2, sort_keys=True) + "\n")

    write_wrapper(blocks, ties)

    print(f"wrote {OUT_DEF.relative_to(REPO)}  ({len(blocks)} pins, "
          f"{sum(len(b['rects']) for b in blocks)} rectangles)")
    print(f"wrote {OUT_JSON.relative_to(REPO)}")
    print(f"  INPUT {len(ins)}   OUTPUT {len(outs)}   INOUT {len(inouts)}")
    print(f"  tied to constants: {len(ties)}   core-driven: {len(data_out)}"
          f"   pad-received: {len(data_in)}")


if __name__ == "__main__":
    main()
