# AUTO-GENERATED by gen_pad_positions.py -- do not hand-edit.
# Source: D03.def/D03/project_defs/ACH/D03_ACH_pad_map.yaml
# Re-run gen_pad_positions.py if that file changes.

set PAD_WEST_LIST {}
lappend PAD_WEST_LIST {u_pad_dvss 500.0}  ;# W07 = VSS
lappend PAD_WEST_LIST {u_pad_clk 575.0}  ;# W08 = clk
lappend PAD_WEST_LIST {u_pad_rst_n 650.0}  ;# W09 = rst_n
lappend PAD_WEST_LIST {u_pad_din_valid 725.0}  ;# W10 = din_valid_i
lappend PAD_WEST_LIST {u_pad_din7 800.0}  ;# W11 = din[7]
lappend PAD_WEST_LIST {u_pad_din6 875.0}  ;# W12 = din[6]
lappend PAD_WEST_LIST {u_pad_din5 950.0}  ;# W13 = din[5]
lappend PAD_WEST_LIST {u_pad_din4 1025.0}  ;# W14 = din[4]
lappend PAD_WEST_LIST {u_pad_din3 1100.0}  ;# W15 = din[3]
lappend PAD_WEST_LIST {u_pad_din2 1175.0}  ;# W16 = din[2]
lappend PAD_WEST_LIST {u_pad_din1 1250.0}  ;# W17 = din[1]
lappend PAD_WEST_LIST {u_pad_din0 1325.0}  ;# W18 = din[0]
lappend PAD_WEST_LIST {u_pad_din_ready 1400.0}  ;# W19 = din_ready_o
lappend PAD_WEST_LIST {u_pad_dout_valid 1475.0}  ;# W20 = dout_valid_o
lappend PAD_WEST_LIST {u_pad_dout7 1550.0}  ;# W21 = dout[7]
lappend PAD_WEST_LIST {u_pad_dout6 1625.0}  ;# W22 = dout[6]

set PAD_NORTH_LIST {}
lappend PAD_NORTH_LIST {u_pad_dout5 500.0}  ;# N01 = dout[5]
lappend PAD_NORTH_LIST {u_pad_dout4 575.0}  ;# N02 = dout[4]
lappend PAD_NORTH_LIST {u_pad_dout3 650.0}  ;# N03 = dout[3]
lappend PAD_NORTH_LIST {u_pad_dout2 725.0}  ;# N04 = dout[2]
lappend PAD_NORTH_LIST {u_pad_dout1 800.0}  ;# N05 = dout[1]
lappend PAD_NORTH_LIST {u_pad_dout0 875.0}  ;# N06 = dout[0]
lappend PAD_NORTH_LIST {u_pad_dvdd 950.0}  ;# N07 = VDD

set PAD_WEST_OCCUPIED  {{500.0 1700.0}}
set PAD_NORTH_OCCUPIED {{500.0 1025.0}}

array set PAD_TIE_INFO {
  u_pad_dvss {W 500.0}
  u_pad_clk {W 575.0}
  u_pad_rst_n {W 650.0}
  u_pad_din_valid {W 725.0}
  u_pad_din7 {W 800.0}
  u_pad_din6 {W 875.0}
  u_pad_din5 {W 950.0}
  u_pad_din4 {W 1025.0}
  u_pad_din3 {W 1100.0}
  u_pad_din2 {W 1175.0}
  u_pad_din1 {W 1250.0}
  u_pad_din0 {W 1325.0}
  u_pad_din_ready {W 1400.0}
  u_pad_dout_valid {W 1475.0}
  u_pad_dout7 {W 1550.0}
  u_pad_dout6 {W 1625.0}
  u_pad_dout5 {N 500.0}
  u_pad_dout4 {N 575.0}
  u_pad_dout3 {N 650.0}
  u_pad_dout2 {N 725.0}
  u_pad_dout1 {N 800.0}
  u_pad_dout0 {N 875.0}
  u_pad_dvdd {N 950.0}
}
set PAD_WEST_ROW_X 350.0
set PAD_NORTH_ROW_Y 2235.0

