/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module counter(clk, rst, q);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] q;
  wire [3:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire \cnt[0] ;
  wire \cnt[1] ;
  wire \cnt[2] ;
  wire \cnt[3] ;
  wire \dout[4] ;
  wire \dout[5] ;
  wire \dout[6] ;
  wire \dout[7] ;
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _28_ (
    .A1(\cnt[0] ),
    .A2(\cnt[1] ),
    .B(\cnt[2] ),
    .ZN(_04_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _29_ (
    .A1(\cnt[0] ),
    .A2(\cnt[1] ),
    .A3(\cnt[2] ),
    .Z(_05_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _30_ (
    .A1(rst),
    .A2(_04_),
    .A3(_05_),
    .ZN(_00_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _31_ (
    .A1(\cnt[3] ),
    .A2(_05_),
    .ZN(_06_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _32_ (
    .A1(rst),
    .A2(_06_),
    .ZN(_01_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _33_ (
    .A1(\cnt[0] ),
    .A2(rst),
    .ZN(_02_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _34_ (
    .A1(\cnt[0] ),
    .A2(\cnt[1] ),
    .ZN(_07_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _35_ (
    .A1(rst),
    .A2(_07_),
    .ZN(_03_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _36_ (
    .CLK(clk),
    .D(_02_),
    .Q(\cnt[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _37_ (
    .CLK(clk),
    .D(_03_),
    .Q(\cnt[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _38_ (
    .CLK(clk),
    .D(_00_),
    .Q(\cnt[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 _39_ (
    .CLK(clk),
    .D(_01_),
    .Q(\cnt[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _40_ (
    .Z(_08_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh _41_ (
    .Z(_09_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _42_ (
    .ZN(_10_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _43_ (
    .ZN(_11_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _44_ (
    .ZN(_12_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _45_ (
    .ZN(_13_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _46_ (
    .ZN(_14_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _47_ (
    .ZN(_15_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _48_ (
    .ZN(_16_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _49_ (
    .ZN(_17_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _50_ (
    .ZN(_18_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _51_ (
    .ZN(_19_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _52_ (
    .ZN(_20_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _53_ (
    .ZN(_21_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _54_ (
    .ZN(_22_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _55_ (
    .ZN(_23_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _56_ (
    .ZN(_24_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _57_ (
    .ZN(_25_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _58_ (
    .ZN(_26_)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _59_ (
    .ZN(_27_)
  );
  gf180mcu_fd_ip_sram__sram64x8m8wm1 u_sram (
    .A({ _11_, _10_, \cnt[3] , \cnt[2] , \cnt[1] , \cnt[0]  }),
    .CEN(_12_),
    .CLK(clk),
    .D({ _19_, _18_, _17_, _16_, _15_, _14_, _13_, _08_ }),
    .GWEN(_09_),
    .Q({ \dout[7] , \dout[6] , \dout[5] , \dout[4] , q }),
    .WEN({ _27_, _26_, _25_, _24_, _23_, _22_, _21_, _20_ })
  );
endmodule
