`timescale 1ns/1ps
`default_nettype none

// AUTO-GENERATED by gen_ach_interface.py -- do not hand-edit.
// Presents the full 135-pin D03 ACH organizer interface.
//
// Per the organizer: every pad control pin must be driven by the
// project block.  The padring instantiates the gf180mcu_fd_io cells;
// this wrapper supplies their control terminals as constants for
// fixed unidirectional operation, and passes data through to the
// frozen butterfold_core.
module butterfold_top #(
    parameter integer TRANSACTION_FIFO_DEPTH = 1,
    parameter integer TX_BYTE_INTERVAL = 1
) (
    input  wire [7:0] din,
    input  wire [7:0] dout_IN,
    input  wire clk,
    input  wire din_ready_o_IN,
    input  wire din_valid_i,
    input  wire dout_valid_o_IN,
    input  wire rst_n,
    output wire [7:0] din_PD,
    output wire [7:0] din_PU,
    output wire [7:0] dout_CS,
    output wire [7:0] dout_IE,
    output wire [7:0] dout_OE,
    output wire [7:0] dout_OUT,
    output wire [7:0] dout_PD,
    output wire [7:0] dout_PDRV0,
    output wire [7:0] dout_PDRV1,
    output wire [7:0] dout_PU,
    output wire [7:0] dout_SL,
    output wire clk_PD,
    output wire clk_PU,
    output wire din_ready_o_CS,
    output wire din_ready_o_IE,
    output wire din_ready_o_OE,
    output wire din_ready_o_OUT,
    output wire din_ready_o_PD,
    output wire din_ready_o_PDRV0,
    output wire din_ready_o_PDRV1,
    output wire din_ready_o_PU,
    output wire din_ready_o_SL,
    output wire din_valid_i_PD,
    output wire din_valid_i_PU,
    output wire dout_valid_o_CS,
    output wire dout_valid_o_IE,
    output wire dout_valid_o_OE,
    output wire dout_valid_o_OUT,
    output wire dout_valid_o_PD,
    output wire dout_valid_o_PDRV0,
    output wire dout_valid_o_PDRV1,
    output wire dout_valid_o_PU,
    output wire dout_valid_o_SL,
    output wire rst_n_PD,
    output wire rst_n_PU
`ifdef USE_POWER_PINS
    , inout wire VDD
    , inout wire VSS
`endif
);

    wire [7:0] core_dout;
    wire       core_din_ready;
    wire       core_dout_valid;

    butterfold_core #(
        .TRANSACTION_FIFO_DEPTH(TRANSACTION_FIFO_DEPTH),
        .TX_BYTE_INTERVAL(TX_BYTE_INTERVAL)
    ) u_core (
        .rst_n(rst_n), .clk(clk), .din(din),
        .din_valid_i(din_valid_i), .din_ready_o(core_din_ready),
        .dout(core_dout), .dout_valid_o(core_dout_valid)
`ifdef USE_POWER_PINS
        , .VDD(VDD), .VSS(VSS)
`endif
    );

    // Data path out to the pad A terminals.
    assign din_ready_o_OUT    = core_din_ready;
    assign dout_OUT           = core_dout;
    assign dout_valid_o_OUT   = core_dout_valid;

    // Pad control strapping: CS=0 SL=0 IE=0 OE=1 PU=0 PD=0
    // PDRV0=1 PDRV1=1 on outputs; PU=0 PD=0 on inputs.
    assign din_PD             = {8{1'b0}};
    assign din_PU             = {8{1'b0}};
    assign dout_CS            = {8{1'b0}};
    assign dout_IE            = {8{1'b0}};
    assign dout_OE            = {8{1'b1}};
    assign dout_PD            = {8{1'b0}};
    assign dout_PDRV0         = {8{1'b1}};
    assign dout_PDRV1         = {8{1'b1}};
    assign dout_PU            = {8{1'b0}};
    assign dout_SL            = {8{1'b0}};
    assign clk_PD             = 1'b0;
    assign clk_PU             = 1'b0;
    assign din_ready_o_CS     = 1'b0;
    assign din_ready_o_IE     = 1'b0;
    assign din_ready_o_OE     = 1'b1;
    assign din_ready_o_PD     = 1'b0;
    assign din_ready_o_PDRV0  = 1'b1;
    assign din_ready_o_PDRV1  = 1'b1;
    assign din_ready_o_PU     = 1'b0;
    assign din_ready_o_SL     = 1'b0;
    assign din_valid_i_PD     = 1'b0;
    assign din_valid_i_PU     = 1'b0;
    assign dout_valid_o_CS    = 1'b0;
    assign dout_valid_o_IE    = 1'b0;
    assign dout_valid_o_OE    = 1'b1;
    assign dout_valid_o_PD    = 1'b0;
    assign dout_valid_o_PDRV0 = 1'b1;
    assign dout_valid_o_PDRV1 = 1'b1;
    assign dout_valid_o_PU    = 1'b0;
    assign dout_valid_o_SL    = 1'b0;
    assign rst_n_PD           = 1'b0;
    assign rst_n_PU           = 1'b0;

endmodule

`default_nettype wire
