`timescale 1ns/1ps
`default_nettype none

module butterfold_top_tb;
    localparam integer N = 128;
    localparam integer DFT12_N = 12;
    localparam integer MAX_WAIT = 200000;

    localparam logic [7:0] CMD_FFT2    = 8'h40;
    localparam logic [7:0] CMD_FFT128  = 8'h41;
    localparam logic [7:0] CMD_IFFT128 = 8'h42;
    localparam logic [7:0] CMD_IFFT2   = 8'h43;
    localparam logic [7:0] CMD_FFT3    = 8'h44;
    localparam logic [7:0] CMD_DFT12   = 8'h45;
    localparam logic [7:0] CMD_RX_SHORT = 8'h46;
    localparam logic [7:0] CMD_RX_LONG  = 8'h47;
    localparam logic [7:0] CMD_TX_SHORT = 8'h48;
    localparam logic [7:0] CMD_TX_LONG  = 8'h49;

    logic clk;
    logic rst_n;
    logic [7:0] din;
    logic din_valid_i;
    logic din_ready_o;
    logic [7:0] dout;
    logic dout_valid_o;

    // Vector memories generated by gen_realtime_vectors.py
    logic [7:0]  two_point_commands [0:7];
    logic [31:0] two_point_inputs   [0:7];
    logic [63:0] two_point_expected [0:7];

    logic [47:0] fft3_inputs   [0:7];
    logic [95:0] fft3_expected [0:7];

    logic [15:0] dft12_inputs   [0:8*12-1];
    logic [31:0] dft12_expected [0:8*12-1];

    logic [15:0] fft128_inputs   [0:5*128-1];
    logic [31:0] fft128_expected [0:5*128-1];
    logic [15:0] ifft128_inputs   [0:5*128-1];
    logic [31:0] ifft128_expected [0:5*128-1];

    logic [15:0] rx_short_inputs [0:4*(9+128)-1];
    logic [15:0] rx_long_inputs  [0:4*(10+128)-1];
    logic [15:0] rx_short_expected [0:4*12-1];
    logic [15:0] rx_long_expected  [0:4*12-1];

    logic [15:0] tx_short_inputs [0:5*12-1];
    logic [15:0] tx_long_inputs  [0:5*12-1];
    logic [15:0] tx_short_expected [0:5*(9+128)-1];
    logic [15:0] tx_long_expected  [0:5*(10+128)-1];

    logic signed [15:0] actual_i [0:127];
    logic signed [15:0] actual_q [0:127];
    logic seen [0:127];

    integer errors;
    integer cycle_count;

    butterfold_top #(
        .TRANSACTION_FIFO_DEPTH(4),
        .TX_BYTE_INTERVAL(1)
    ) dut (
        .rst_n        (rst_n),
        .clk          (clk),
        .din          (din),
        .din_valid_i  (din_valid_i),
        .din_ready_o  (din_ready_o),
        .dout         (dout),
        .dout_valid_o (dout_valid_o)
    );

    always #5 clk = ~clk;
    always @(posedge clk) cycle_count <= cycle_count + 1;

    task automatic send_byte(input logic [7:0] value);
        integer wait_count;
        logic accepted;
        begin
            @(negedge clk);
            din <= value;
            din_valid_i <= 1'b1;
            wait_count = 0;
            accepted = 1'b0;
            while (!accepted) begin
                @(posedge clk);
                if (din_valid_i && din_ready_o)
                    accepted = 1'b1;
                else begin
                    wait_count = wait_count + 1;
                    if (wait_count > MAX_WAIT)
                        $fatal(1, "Timeout sending byte %02h", value);
                end
            end
            @(negedge clk);
            din_valid_i <= 1'b0;
            din <= 8'h00;
        end
    endtask

    task automatic recv_byte(output logic [7:0] value);
        integer wait_count;
        logic received;
        begin
            wait_count = 0;
            received = 1'b0;
            while (!received) begin
                @(posedge clk);
                if (dout_valid_o) begin
                    value = dout;
                    received = 1'b1;
                end else begin
                    wait_count = wait_count + 1;
                    if (wait_count > MAX_WAIT)
                        $fatal(1, "Timeout waiting for dout byte");
                end
            end
        end
    endtask

    // One standalone complex output record:
    // address, I high, I low, Q high, Q low.
    task automatic recv_complex_record(
        output logic [6:0] addr,
        output logic signed [15:0] value_i,
        output logic signed [15:0] value_q
    );
        logic [7:0] b0, b1, b2, b3, b4;
        begin
            recv_byte(b0);
            recv_byte(b1);
            recv_byte(b2);
            recv_byte(b3);
            recv_byte(b4);
            addr = b0[6:0];
            value_i = $signed({b1,b2});
            value_q = $signed({b3,b4});
        end
    endtask

    task automatic clear_actual;
        integer k;
        begin
            for (k=0; k<128; k=k+1) begin
                actual_i[k] = '0;
                actual_q[k] = '0;
                seen[k] = 1'b0;
            end
        end
    endtask

    task automatic run_two_point(input integer test_index);
        logic [6:0] addr;
        logic signed [15:0] vi, vq;
        logic signed [15:0] exp_i [0:1];
        logic signed [15:0] exp_q [0:1];
        integer r;
        begin
            clear_actual();
            send_byte(two_point_commands[test_index]);
            send_byte(two_point_inputs[test_index][31:24]);
            send_byte(two_point_inputs[test_index][23:16]);
            send_byte(two_point_inputs[test_index][15:8]);
            send_byte(two_point_inputs[test_index][7:0]);

            for (r=0; r<2; r=r+1) begin
                recv_complex_record(addr, vi, vq);
                if (addr > 1) begin
                    $display("2PT invalid address %0d", addr); errors=errors+1;
                end else begin
                    actual_i[addr]=vi; actual_q[addr]=vq; seen[addr]=1'b1;
                end
            end
            exp_i[0] = $signed(two_point_expected[test_index][63:48]);
            exp_q[0] = $signed(two_point_expected[test_index][47:32]);
            exp_i[1] = $signed(two_point_expected[test_index][31:16]);
            exp_q[1] = $signed(two_point_expected[test_index][15:0]);
            for (r=0; r<2; r=r+1) begin
                if (!seen[r] || actual_i[r] !== exp_i[r] || actual_q[r] !== exp_q[r]) begin
                    $display("2PT mismatch bin %0d expected=(%0d,%0d) actual=(%0d,%0d)",
                        r, exp_i[r], exp_q[r], actual_i[r], actual_q[r]);
                    errors=errors+1;
                end
            end
            $display("PASS interface exercise: %s", two_point_commands[test_index]==CMD_FFT2 ? "FFT2" : "IFFT2");
        end
    endtask

    task automatic run_fft3;
        logic [6:0] addr;
        logic signed [15:0] vi, vq;
        logic signed [15:0] ei, eq;
        integer r;
        begin
            clear_actual();
            send_byte(CMD_FFT3);
            for (r=5; r>=0; r=r-1)
                send_byte(fft3_inputs[0][r*8 +: 8]);
            for (r=0; r<3; r=r+1) begin
                recv_complex_record(addr,vi,vq);
                actual_i[addr]=vi; actual_q[addr]=vq; seen[addr]=1'b1;
            end
            for (r=0; r<3; r=r+1) begin
                case (r)
                    0: begin ei=$signed(fft3_expected[0][95:80]); eq=$signed(fft3_expected[0][79:64]); end
                    1: begin ei=$signed(fft3_expected[0][63:48]); eq=$signed(fft3_expected[0][47:32]); end
                    default: begin ei=$signed(fft3_expected[0][31:16]); eq=$signed(fft3_expected[0][15:0]); end
                endcase
                if (!seen[r] || actual_i[r]!==ei || actual_q[r]!==eq) begin
                    $display("FFT3 mismatch bin %0d",r); errors=errors+1;
                end
            end
            $display("PASS interface exercise: FFT3");
        end
    endtask

    task automatic run_block_standalone(
        input logic [7:0] command,
        input integer size,
        input integer input_base,
        input integer expected_base
    );
        logic [6:0] addr;
        logic signed [15:0] vi,vq,ei,eq;
        integer k;
        begin
            clear_actual();
            send_byte(command);
            for (k=0;k<size;k=k+1) begin
                if (command==CMD_DFT12) begin
                    send_byte(dft12_inputs[input_base+k][15:8]);
                    send_byte(dft12_inputs[input_base+k][7:0]);
                end else if (command==CMD_FFT128) begin
                    send_byte(fft128_inputs[input_base+k][15:8]);
                    send_byte(fft128_inputs[input_base+k][7:0]);
                end else begin
                    send_byte(ifft128_inputs[input_base+k][15:8]);
                    send_byte(ifft128_inputs[input_base+k][7:0]);
                end
            end
            for (k=0;k<size;k=k+1) begin
                recv_complex_record(addr,vi,vq);
                if (addr >= size || seen[addr]) begin
                    $display("Standalone block command %02h bad/duplicate address %0d",command,addr);
                    errors=errors+1;
                end else begin
                    actual_i[addr]=vi; actual_q[addr]=vq; seen[addr]=1'b1;
                end
            end
            for (k=0;k<size;k=k+1) begin
                if (command==CMD_DFT12) begin
                    ei=$signed(dft12_expected[expected_base+k][31:16]);
                    eq=$signed(dft12_expected[expected_base+k][15:0]);
                end else if (command==CMD_FFT128) begin
                    ei=$signed(fft128_expected[expected_base+k][31:16]);
                    eq=$signed(fft128_expected[expected_base+k][15:0]);
                end else begin
                    ei=$signed(ifft128_expected[expected_base+k][31:16]);
                    eq=$signed(ifft128_expected[expected_base+k][15:0]);
                end
                if (!seen[k] || actual_i[k]!==ei || actual_q[k]!==eq) begin
                    $display("Standalone block command %02h mismatch bin %0d expected=(%0d,%0d) actual=(%0d,%0d)",
                        command,k,ei,eq,actual_i[k],actual_q[k]);
                    errors=errors+1;
                end
            end
            $display("PASS interface exercise: command 0x%02h",command);
        end
    endtask

    task automatic run_rx(input logic [7:0] command, input logic long_cp);
        integer count, k;
        logic [7:0] b;
        logic [15:0] e;
        begin
            count = long_cp ? 138 : 137;
            send_byte(command);
            for (k=0;k<count;k=k+1) begin
                if (long_cp) begin
                    send_byte(rx_long_inputs[k][15:8]);
                    send_byte(rx_long_inputs[k][7:0]);
                end else begin
                    send_byte(rx_short_inputs[k][15:8]);
                    send_byte(rx_short_inputs[k][7:0]);
                end
            end
            for (k=0;k<12;k=k+1) begin
                e = long_cp ? rx_long_expected[k] : rx_short_expected[k];
                recv_byte(b); if (b!==e[15:8]) begin $display("RX %02h I byte mismatch %0d",command,k); errors=errors+1; end
                recv_byte(b); if (b!==e[7:0])  begin $display("RX %02h Q byte mismatch %0d",command,k); errors=errors+1; end
            end
            $display("PASS interface exercise: OFDM_RX 0x%02h",command);
        end
    endtask

    task automatic run_tx(input logic [7:0] command, input logic long_cp);
        integer out_samples, k;
        logic [7:0] b;
        logic [15:0] e;
        begin
            out_samples = long_cp ? 138 : 137;
            send_byte(command);
            for (k=0;k<12;k=k+1) begin
                if (long_cp) begin
                    send_byte(tx_long_inputs[k][15:8]);
                    send_byte(tx_long_inputs[k][7:0]);
                end else begin
                    send_byte(tx_short_inputs[k][15:8]);
                    send_byte(tx_short_inputs[k][7:0]);
                end
            end
            for (k=0;k<out_samples;k=k+1) begin
                e = long_cp ? tx_long_expected[k] : tx_short_expected[k];
                recv_byte(b); if (b!==e[15:8]) begin $display("TX %02h I byte mismatch %0d",command,k); errors=errors+1; end
                recv_byte(b); if (b!==e[7:0])  begin $display("TX %02h Q byte mismatch %0d",command,k); errors=errors+1; end
            end
            $display("PASS interface exercise: OFDM_TX 0x%02h",command);
        end
    endtask

    initial begin
        clk=1'b0; rst_n=1'b0; din=8'h00; din_valid_i=1'b0;
        errors=0; cycle_count=0;

        $readmemh("vectors/two_point_commands.hex", two_point_commands);
        $readmemh("vectors/two_point_inputs.hex", two_point_inputs);
        $readmemh("vectors/two_point_expected.hex", two_point_expected);
        $readmemh("vectors/fft3_inputs.hex", fft3_inputs);
        $readmemh("vectors/fft3_expected.hex", fft3_expected);
        $readmemh("vectors/dft12_inputs.hex", dft12_inputs);
        $readmemh("vectors/dft12_expected.hex", dft12_expected);
        $readmemh("vectors/fft128_inputs.hex", fft128_inputs);
        $readmemh("vectors/fft128_expected.hex", fft128_expected);
        $readmemh("vectors/ifft128_inputs.hex", ifft128_inputs);
        $readmemh("vectors/ifft128_expected.hex", ifft128_expected);
        $readmemh("vectors/ofdm_rx_short_normal_cp_inputs.hex", rx_short_inputs);
        $readmemh("vectors/ofdm_rx_long_normal_cp_inputs.hex", rx_long_inputs);
        $readmemh("vectors/ofdm_rx_short_normal_cp_expected_rb.hex", rx_short_expected);
        $readmemh("vectors/ofdm_rx_long_normal_cp_expected_rb.hex", rx_long_expected);
        $readmemh("vectors/ofdm_tx_short_normal_cp_inputs.hex", tx_short_inputs);
        $readmemh("vectors/ofdm_tx_long_normal_cp_inputs.hex", tx_long_inputs);
        $readmemh("vectors/ofdm_tx_short_normal_cp_expected.hex", tx_short_expected);
        $readmemh("vectors/ofdm_tx_long_normal_cp_expected.hex", tx_long_expected);

        repeat(6) @(posedge clk);
        rst_n=1'b1;
        repeat(3) @(posedge clk);

        $display("============================================================");
        $display("ButterFold FINAL-PIN regression");
        $display("Only din/din_valid/din_ready and dout/dout_valid are used.");
        $display("============================================================");

        run_two_point(0); // FFT2
        run_two_point(1); // IFFT2
        run_fft3();
        run_block_standalone(CMD_DFT12,12,0,0);
        run_block_standalone(CMD_FFT128,128,0,0);
        run_block_standalone(CMD_IFFT128,128,0,0);
        run_rx(CMD_RX_SHORT,1'b0);
        run_rx(CMD_RX_LONG,1'b1);
        run_tx(CMD_TX_SHORT,1'b0);
        run_tx(CMD_TX_LONG,1'b1);

        $display("============================================================");
        if (errors==0)
            $display("FINAL-PIN OVERALL RESULT: PASS");
        else
            $display("FINAL-PIN OVERALL RESULT: FAIL (%0d errors)",errors);
        $display("============================================================");
        $finish;
    end

endmodule

`default_nettype wire
