/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module butterfold_top_control(rst_n, clk, din, din_valid_i, din_ready_o, dout, dout_valid_o, core_din_valid_o, core_din_ready_i, core_dout_i, core_dout_valid_i, core_result_ready_o, standalone_active_o, serializer_ready_i, serializer_valid_i, serializer_job_done_i, serializer_dout_i, debug_mode_o, debug_req_o, debug_write_o, debug_addr_o
, debug_wdata_o, debug_ready_i, debug_rdata_i, debug_rvalid_i, ext_state, external_fire, feeder_start, job_push, job_head_command, core_ofdm_active, drain_active, core_rx_selected_complete, core_rx_complete, core_tx_complete, top_state_o);
  input rst_n;
  wire rst_n;
  input clk;
  wire clk;
  input [7:0] din;
  wire [7:0] din;
  input din_valid_i;
  wire din_valid_i;
  output din_ready_o;
  wire din_ready_o;
  output [7:0] dout;
  wire [7:0] dout;
  output dout_valid_o;
  wire dout_valid_o;
  output core_din_valid_o;
  wire core_din_valid_o;
  input core_din_ready_i;
  wire core_din_ready_i;
  input [7:0] core_dout_i;
  wire [7:0] core_dout_i;
  input core_dout_valid_i;
  wire core_dout_valid_i;
  output core_result_ready_o;
  wire core_result_ready_o;
  output standalone_active_o;
  wire standalone_active_o;
  input serializer_ready_i;
  wire serializer_ready_i;
  input serializer_valid_i;
  wire serializer_valid_i;
  input serializer_job_done_i;
  wire serializer_job_done_i;
  input [7:0] serializer_dout_i;
  wire [7:0] serializer_dout_i;
  output debug_mode_o;
  wire debug_mode_o;
  output debug_req_o;
  wire debug_req_o;
  output debug_write_o;
  wire debug_write_o;
  output [7:0] debug_addr_o;
  wire [7:0] debug_addr_o;
  output [15:0] debug_wdata_o;
  wire [15:0] debug_wdata_o;
  input debug_ready_i;
  wire debug_ready_i;
  input [15:0] debug_rdata_i;
  wire [15:0] debug_rdata_i;
  input debug_rvalid_i;
  wire debug_rvalid_i;
  output [2:0] ext_state;
  wire [2:0] ext_state;
  output external_fire;
  wire external_fire;
  output feeder_start;
  wire feeder_start;
  output job_push;
  wire job_push;
  output [7:0] job_head_command;
  wire [7:0] job_head_command;
  output core_ofdm_active;
  wire core_ofdm_active;
  output drain_active;
  wire drain_active;
  output core_rx_selected_complete;
  wire core_rx_selected_complete;
  output core_rx_complete;
  wire core_rx_complete;
  output core_tx_complete;
  wire core_tx_complete;
  output [4:0] top_state_o;
  wire [4:0] top_state_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire \debug_data_hi[0] ;
  wire \debug_data_hi[1] ;
  wire \debug_data_hi[2] ;
  wire \debug_data_hi[3] ;
  wire \debug_data_hi[4] ;
  wire \debug_data_hi[5] ;
  wire \debug_data_hi[6] ;
  wire \debug_data_hi[7] ;
  wire \debug_read_latch[0] ;
  wire \debug_read_latch[10] ;
  wire \debug_read_latch[11] ;
  wire \debug_read_latch[12] ;
  wire \debug_read_latch[13] ;
  wire \debug_read_latch[14] ;
  wire \debug_read_latch[15] ;
  wire \debug_read_latch[1] ;
  wire \debug_read_latch[2] ;
  wire \debug_read_latch[3] ;
  wire \debug_read_latch[4] ;
  wire \debug_read_latch[5] ;
  wire \debug_read_latch[6] ;
  wire \debug_read_latch[7] ;
  wire \debug_read_latch[8] ;
  wire \debug_read_latch[9] ;
  wire \echo_data[0] ;
  wire \echo_data[1] ;
  wire \echo_data[2] ;
  wire \echo_data[3] ;
  wire \echo_data[4] ;
  wire \echo_data[5] ;
  wire \echo_data[6] ;
  wire \echo_data[7] ;
  wire \input_left[0] ;
  wire \input_left[1] ;
  wire \input_left[2] ;
  wire \input_left[3] ;
  wire \input_left[4] ;
  wire \input_left[5] ;
  wire \input_left[6] ;
  wire \input_left[7] ;
  wire \input_left[8] ;
  wire \magic_index[0] ;
  wire \magic_index[1] ;
  wire \magic_index[2] ;
  wire \output_left[0] ;
  wire \output_left[1] ;
  wire \output_left[2] ;
  wire \output_left[3] ;
  wire \output_left[4] ;
  wire \output_left[5] ;
  wire \output_left[6] ;
  wire \output_left[7] ;
  wire \output_left[8] ;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _367_ (
    .I(core_dout_valid_i),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _368_ (
    .I(\output_left[0] ),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _369_ (
    .I(\output_left[6] ),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _370_ (
    .I(\output_left[7] ),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _371_ (
    .I(\output_left[5] ),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _372_ (
    .I(job_head_command[3]),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _373_ (
    .I(job_head_command[6]),
    .ZN(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _374_ (
    .I(top_state_o[0]),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _375_ (
    .I(top_state_o[1]),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _376_ (
    .I(top_state_o[2]),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _377_ (
    .I(top_state_o[3]),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _378_ (
    .I(din_valid_i),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _379_ (
    .I(\input_left[0] ),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _380_ (
    .I(\input_left[2] ),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _381_ (
    .I(\input_left[3] ),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _382_ (
    .I(\input_left[5] ),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _383_ (
    .I(\input_left[4] ),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _384_ (
    .I(top_state_o[4]),
    .ZN(_112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _385_ (
    .I(din[2]),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _386_ (
    .I(din[1]),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _387_ (
    .I(din[4]),
    .ZN(_115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _388_ (
    .I(din[5]),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _389_ (
    .I(din[0]),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _390_ (
    .I(din[7]),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _391_ (
    .I(\magic_index[1] ),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _392_ (
    .I(\magic_index[0] ),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _393_ (
    .I(\magic_index[2] ),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _394_ (
    .I(serializer_ready_i),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _395_ (
    .I(serializer_dout_i[0]),
    .ZN(_123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _396_ (
    .I(serializer_dout_i[1]),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _397_ (
    .I(serializer_dout_i[4]),
    .ZN(_125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _398_ (
    .I(core_dout_i[6]),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _399_ (
    .A1(_101_),
    .A2(job_head_command[7]),
    .A3(job_head_command[4]),
    .A4(job_head_command[5]),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _400_ (
    .A1(job_head_command[1]),
    .A2(_100_),
    .A3(job_head_command[2]),
    .Z(_128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _401_ (
    .A1(\output_left[6] ),
    .A2(\output_left[7] ),
    .A3(\output_left[5] ),
    .A4(\output_left[4] ),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _402_ (
    .A1(\output_left[2] ),
    .A2(\output_left[3] ),
    .A3(\output_left[8] ),
    .ZN(_130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _403_ (
    .A1(core_ofdm_active),
    .A2(core_dout_valid_i),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _404_ (
    .A1(\output_left[1] ),
    .A2(_096_),
    .A3(_131_),
    .ZN(_132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _405_ (
    .A1(_129_),
    .A2(_130_),
    .A3(_132_),
    .Z(_133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _406_ (
    .A1(top_state_o[2]),
    .A2(top_state_o[3]),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _407_ (
    .A1(top_state_o[2]),
    .A2(top_state_o[3]),
    .Z(_135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _408_ (
    .A1(top_state_o[0]),
    .A2(_103_),
    .A3(top_state_o[4]),
    .A4(_135_),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _409_ (
    .A1(_102_),
    .A2(top_state_o[1]),
    .A3(_112_),
    .A4(_134_),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _410_ (
    .A1(_133_),
    .A2(_136_),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _411_ (
    .A1(_127_),
    .A2(_128_),
    .B(_138_),
    .ZN(_001_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _412_ (
    .A1(_127_),
    .A2(_128_),
    .A3(_133_),
    .A4(_136_),
    .Z(_000_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _413_ (
    .A1(top_state_o[1]),
    .A2(top_state_o[4]),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _414_ (
    .A1(top_state_o[1]),
    .A2(top_state_o[4]),
    .Z(_140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _415_ (
    .A1(_135_),
    .A2(_140_),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _416_ (
    .I(_141_),
    .ZN(ext_state[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _417_ (
    .A1(core_din_ready_i),
    .A2(_141_),
    .Z(_142_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _418_ (
    .A1(core_din_ready_i),
    .A2(_141_),
    .ZN(_143_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _419_ (
    .A1(_102_),
    .A2(_103_),
    .A3(top_state_o[4]),
    .ZN(_144_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _420_ (
    .A1(top_state_o[0]),
    .A2(top_state_o[1]),
    .A3(_112_),
    .ZN(_145_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _421_ (
    .A1(_104_),
    .A2(top_state_o[3]),
    .ZN(_146_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _422_ (
    .A1(_104_),
    .A2(top_state_o[3]),
    .ZN(_147_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _423_ (
    .A1(top_state_o[2]),
    .A2(_105_),
    .ZN(_148_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _424_ (
    .A1(top_state_o[0]),
    .A2(_103_),
    .A3(_104_),
    .A4(top_state_o[4]),
    .ZN(_149_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _425_ (
    .A1(_102_),
    .A2(top_state_o[1]),
    .A3(top_state_o[2]),
    .A4(_112_),
    .ZN(_150_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _426_ (
    .A1(_145_),
    .A2(_146_),
    .B1(_150_),
    .B2(top_state_o[3]),
    .ZN(_151_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _427_ (
    .A1(top_state_o[2]),
    .A2(top_state_o[3]),
    .ZN(_152_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _428_ (
    .A1(_140_),
    .A2(_152_),
    .ZN(_153_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _429_ (
    .A1(top_state_o[2]),
    .A2(top_state_o[3]),
    .A3(_139_),
    .ZN(_154_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _430_ (
    .A1(_145_),
    .A2(_146_),
    .B(_154_),
    .ZN(_155_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _431_ (
    .A1(_104_),
    .A2(_144_),
    .B1(_149_),
    .B2(_105_),
    .C(_153_),
    .ZN(_156_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _432_ (
    .A1(top_state_o[2]),
    .A2(_145_),
    .B1(_150_),
    .B2(top_state_o[3]),
    .C(_154_),
    .ZN(_157_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _433_ (
    .A1(_143_),
    .A2(_156_),
    .ZN(din_ready_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _434_ (
    .A1(_142_),
    .A2(_157_),
    .B(din_valid_i),
    .ZN(_158_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _435_ (
    .I(_158_),
    .ZN(external_fire)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _436_ (
    .A1(\input_left[5] ),
    .A2(\input_left[4] ),
    .ZN(_159_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _437_ (
    .A1(\input_left[2] ),
    .A2(\input_left[3] ),
    .A3(\input_left[6] ),
    .A4(\input_left[7] ),
    .ZN(_160_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _438_ (
    .A1(_107_),
    .A2(\input_left[1] ),
    .A3(\input_left[8] ),
    .ZN(_161_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _439_ (
    .A1(external_fire),
    .A2(_159_),
    .A3(_160_),
    .A4(_161_),
    .Z(_162_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _440_ (
    .A1(top_state_o[0]),
    .A2(_139_),
    .ZN(_163_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _441_ (
    .A1(_102_),
    .A2(ext_state[1]),
    .ZN(_164_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _442_ (
    .A1(top_state_o[0]),
    .A2(_141_),
    .ZN(_165_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _443_ (
    .A1(job_head_command[1]),
    .A2(job_head_command[2]),
    .B(job_head_command[4]),
    .C(job_head_command[3]),
    .ZN(_166_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _444_ (
    .A1(job_head_command[1]),
    .A2(job_head_command[2]),
    .B(job_head_command[3]),
    .ZN(_167_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _445_ (
    .A1(_127_),
    .A2(_167_),
    .ZN(_168_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _446_ (
    .A1(_165_),
    .A2(_166_),
    .A3(_168_),
    .ZN(_169_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _447_ (
    .A1(_162_),
    .A2(_169_),
    .Z(_002_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _448_ (
    .A1(_146_),
    .A2(_163_),
    .ZN(_170_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _449_ (
    .A1(top_state_o[0]),
    .A2(_140_),
    .ZN(_171_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _450_ (
    .A1(_147_),
    .A2(_171_),
    .Z(_172_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _451_ (
    .A1(_148_),
    .A2(_163_),
    .ZN(_173_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _452_ (
    .A1(_170_),
    .A2(_172_),
    .A3(_173_),
    .ZN(_174_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _453_ (
    .A1(top_state_o[0]),
    .A2(_103_),
    .A3(top_state_o[4]),
    .A4(_146_),
    .ZN(_175_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _454_ (
    .A1(serializer_valid_i),
    .A2(_175_),
    .ZN(_176_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _455_ (
    .A1(_145_),
    .A2(_152_),
    .ZN(_177_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _456_ (
    .A1(core_dout_valid_i),
    .A2(_177_),
    .ZN(_178_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _457_ (
    .A1(_174_),
    .A2(_176_),
    .A3(_178_),
    .ZN(dout_valid_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _458_ (
    .A1(top_state_o[0]),
    .A2(_103_),
    .A3(top_state_o[4]),
    .A4(_152_),
    .ZN(debug_write_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _459_ (
    .A1(top_state_o[0]),
    .A2(ext_state[1]),
    .ZN(_179_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _460_ (
    .I(_179_),
    .ZN(ext_state[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _461_ (
    .A1(_158_),
    .A2(_179_),
    .ZN(_180_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _462_ (
    .A1(_133_),
    .A2(_137_),
    .ZN(_181_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _463_ (
    .A1(din[6]),
    .A2(_116_),
    .A3(_118_),
    .ZN(_182_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _464_ (
    .A1(din[3]),
    .A2(_115_),
    .ZN(_183_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _465_ (
    .A1(_113_),
    .A2(din[3]),
    .A3(_115_),
    .ZN(_184_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _466_ (
    .A1(_182_),
    .A2(_184_),
    .ZN(_185_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _467_ (
    .A1(din[1]),
    .A2(_182_),
    .A3(_184_),
    .ZN(_186_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _468_ (
    .A1(_114_),
    .A2(_185_),
    .ZN(_187_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _469_ (
    .A1(din[3]),
    .A2(din[4]),
    .ZN(_188_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _470_ (
    .A1(din[3]),
    .A2(din[4]),
    .A3(_182_),
    .ZN(_189_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _471_ (
    .A1(din[6]),
    .A2(_116_),
    .A3(_118_),
    .A4(_188_),
    .ZN(_190_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _472_ (
    .A1(din[1]),
    .A2(_182_),
    .A3(_184_),
    .B(_190_),
    .ZN(_191_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _473_ (
    .A1(ext_state[0]),
    .A2(_191_),
    .Z(_192_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _474_ (
    .A1(_143_),
    .A2(_156_),
    .B(ext_state[0]),
    .C(_106_),
    .ZN(_193_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _475_ (
    .A1(_136_),
    .A2(_193_),
    .B(_192_),
    .ZN(_194_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _476_ (
    .A1(\output_left[1] ),
    .A2(\output_left[0] ),
    .ZN(_195_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _477_ (
    .A1(\output_left[1] ),
    .A2(\output_left[0] ),
    .A3(\output_left[2] ),
    .A4(\output_left[3] ),
    .Z(_196_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _478_ (
    .I(_196_),
    .ZN(_197_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _479_ (
    .A1(\output_left[4] ),
    .A2(_196_),
    .ZN(_198_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _480_ (
    .A1(\output_left[4] ),
    .A2(_196_),
    .ZN(_199_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _481_ (
    .A1(_137_),
    .A2(_199_),
    .ZN(_200_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _482_ (
    .A1(_198_),
    .A2(_200_),
    .ZN(_201_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _483_ (
    .A1(_113_),
    .A2(_114_),
    .ZN(_202_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _484_ (
    .A1(_113_),
    .A2(_114_),
    .A3(_190_),
    .ZN(_203_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _485_ (
    .A1(_136_),
    .A2(_203_),
    .Z(_204_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _486_ (
    .A1(_186_),
    .A2(_204_),
    .B(_201_),
    .ZN(_205_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _487_ (
    .A1(_181_),
    .A2(_194_),
    .A3(_205_),
    .ZN(feeder_start)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _488_ (
    .A1(core_ofdm_active),
    .A2(_136_),
    .Z(drain_active)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _489_ (
    .A1(_179_),
    .A2(_191_),
    .B(_164_),
    .ZN(_206_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _490_ (
    .A1(_106_),
    .A2(_206_),
    .ZN(core_din_valid_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _491_ (
    .A1(_144_),
    .A2(_147_),
    .B(debug_write_o),
    .ZN(_207_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _492_ (
    .I(_207_),
    .ZN(debug_req_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _493_ (
    .A1(top_state_o[3]),
    .A2(_171_),
    .ZN(_208_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _494_ (
    .A1(top_state_o[2]),
    .A2(_208_),
    .B(_207_),
    .ZN(debug_mode_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _495_ (
    .A1(standalone_active_o),
    .A2(_122_),
    .ZN(core_result_ready_o)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _496_ (
    .A1(\debug_read_latch[8] ),
    .A2(_170_),
    .B1(_172_),
    .B2(\echo_data[0] ),
    .C1(_175_),
    .C2(\debug_read_latch[0] ),
    .ZN(_209_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _497_ (
    .A1(core_dout_valid_i),
    .A2(_209_),
    .ZN(_210_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _498_ (
    .A1(core_dout_valid_i),
    .A2(core_dout_i[0]),
    .B(_210_),
    .C(serializer_valid_i),
    .ZN(_211_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _499_ (
    .A1(serializer_valid_i),
    .A2(_123_),
    .B(_211_),
    .ZN(dout[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _500_ (
    .A1(\magic_index[1] ),
    .A2(\magic_index[2] ),
    .ZN(_212_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _501_ (
    .A1(\debug_read_latch[9] ),
    .A2(_170_),
    .B1(_172_),
    .B2(\echo_data[1] ),
    .ZN(_213_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _502_ (
    .A1(\debug_read_latch[1] ),
    .A2(_175_),
    .B1(_212_),
    .B2(_173_),
    .ZN(_214_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _503_ (
    .A1(_213_),
    .A2(_214_),
    .B(core_dout_valid_i),
    .ZN(_215_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _504_ (
    .A1(core_dout_valid_i),
    .A2(core_dout_i[1]),
    .B(_215_),
    .C(serializer_valid_i),
    .ZN(_216_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _505_ (
    .A1(serializer_valid_i),
    .A2(_124_),
    .B(_216_),
    .ZN(dout[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _506_ (
    .A1(serializer_valid_i),
    .A2(serializer_dout_i[2]),
    .ZN(_217_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _507_ (
    .A1(_120_),
    .A2(_212_),
    .ZN(_218_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _508_ (
    .A1(\debug_read_latch[2] ),
    .A2(_175_),
    .B1(_218_),
    .B2(_173_),
    .ZN(_219_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _509_ (
    .A1(\debug_read_latch[10] ),
    .A2(_170_),
    .B1(_172_),
    .B2(\echo_data[2] ),
    .ZN(_220_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _510_ (
    .A1(_178_),
    .A2(_219_),
    .A3(_220_),
    .ZN(_221_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _511_ (
    .A1(_095_),
    .A2(core_dout_i[2]),
    .B(_221_),
    .ZN(_222_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _512_ (
    .A1(serializer_valid_i),
    .A2(_222_),
    .B(_217_),
    .ZN(dout[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _513_ (
    .A1(serializer_valid_i),
    .A2(serializer_dout_i[3]),
    .ZN(_223_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _514_ (
    .A1(_119_),
    .A2(\magic_index[0] ),
    .A3(\magic_index[2] ),
    .ZN(_224_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _515_ (
    .A1(\echo_data[3] ),
    .A2(_172_),
    .B1(_173_),
    .B2(_224_),
    .C1(_175_),
    .C2(\debug_read_latch[3] ),
    .ZN(_225_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _516_ (
    .A1(\debug_read_latch[11] ),
    .A2(_170_),
    .ZN(_226_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _517_ (
    .A1(_178_),
    .A2(_225_),
    .A3(_226_),
    .ZN(_227_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _518_ (
    .A1(_095_),
    .A2(core_dout_i[3]),
    .B(_227_),
    .ZN(_228_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _519_ (
    .A1(serializer_valid_i),
    .A2(_228_),
    .B(_223_),
    .ZN(dout[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi222_1 _520_ (
    .A1(\debug_read_latch[12] ),
    .A2(_170_),
    .B1(_172_),
    .B2(\echo_data[4] ),
    .C1(_175_),
    .C2(\debug_read_latch[4] ),
    .ZN(_229_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _521_ (
    .A1(core_dout_valid_i),
    .A2(_229_),
    .ZN(_230_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _522_ (
    .A1(core_dout_valid_i),
    .A2(core_dout_i[4]),
    .B(_230_),
    .C(serializer_valid_i),
    .ZN(_231_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _523_ (
    .A1(serializer_valid_i),
    .A2(_125_),
    .B(_231_),
    .ZN(dout[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _524_ (
    .A1(\echo_data[5] ),
    .A2(_172_),
    .ZN(_232_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _525_ (
    .A1(\debug_read_latch[13] ),
    .A2(_170_),
    .B1(_175_),
    .B2(\debug_read_latch[5] ),
    .ZN(_233_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _526_ (
    .A1(_178_),
    .A2(_232_),
    .A3(_233_),
    .ZN(_234_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _527_ (
    .A1(_095_),
    .A2(core_dout_i[5]),
    .B(_234_),
    .ZN(_235_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _528_ (
    .A1(serializer_valid_i),
    .A2(serializer_dout_i[5]),
    .ZN(_236_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _529_ (
    .A1(serializer_valid_i),
    .A2(_235_),
    .B(_236_),
    .ZN(dout[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _530_ (
    .A1(\debug_read_latch[6] ),
    .A2(_175_),
    .B(_173_),
    .C(core_dout_valid_i),
    .ZN(_237_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _531_ (
    .A1(\debug_read_latch[14] ),
    .A2(_170_),
    .B1(_172_),
    .B2(\echo_data[6] ),
    .ZN(_238_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _532_ (
    .A1(core_dout_valid_i),
    .A2(_126_),
    .B1(_237_),
    .B2(_238_),
    .C(serializer_valid_i),
    .ZN(_239_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _533_ (
    .A1(serializer_valid_i),
    .A2(serializer_dout_i[6]),
    .B(_239_),
    .ZN(_240_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _534_ (
    .I(_240_),
    .ZN(dout[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _535_ (
    .A1(\debug_read_latch[15] ),
    .A2(_170_),
    .ZN(_241_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _536_ (
    .A1(\echo_data[7] ),
    .A2(_172_),
    .B1(_175_),
    .B2(\debug_read_latch[7] ),
    .ZN(_242_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _537_ (
    .A1(_178_),
    .A2(_241_),
    .A3(_242_),
    .ZN(_243_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _538_ (
    .A1(_095_),
    .A2(core_dout_i[7]),
    .B(_243_),
    .ZN(_244_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _539_ (
    .A1(serializer_valid_i),
    .A2(serializer_dout_i[7]),
    .ZN(_245_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _540_ (
    .A1(serializer_valid_i),
    .A2(_244_),
    .B(_245_),
    .ZN(dout[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _541_ (
    .A1(_104_),
    .A2(top_state_o[3]),
    .A3(debug_rvalid_i),
    .A4(_171_),
    .ZN(_246_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _542_ (
    .I0(debug_rdata_i[3]),
    .I1(\debug_read_latch[3] ),
    .S(_246_),
    .Z(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _543_ (
    .I0(debug_rdata_i[4]),
    .I1(\debug_read_latch[4] ),
    .S(_246_),
    .Z(_004_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _544_ (
    .I0(debug_rdata_i[5]),
    .I1(\debug_read_latch[5] ),
    .S(_246_),
    .Z(_005_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _545_ (
    .I0(debug_rdata_i[6]),
    .I1(\debug_read_latch[6] ),
    .S(_246_),
    .Z(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _546_ (
    .I0(debug_rdata_i[7]),
    .I1(\debug_read_latch[7] ),
    .S(_246_),
    .Z(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _547_ (
    .I0(debug_rdata_i[8]),
    .I1(\debug_read_latch[8] ),
    .S(_246_),
    .Z(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _548_ (
    .I0(debug_rdata_i[9]),
    .I1(\debug_read_latch[9] ),
    .S(_246_),
    .Z(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _549_ (
    .I0(debug_rdata_i[10]),
    .I1(\debug_read_latch[10] ),
    .S(_246_),
    .Z(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _550_ (
    .I0(debug_rdata_i[11]),
    .I1(\debug_read_latch[11] ),
    .S(_246_),
    .Z(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _551_ (
    .I0(debug_rdata_i[12]),
    .I1(\debug_read_latch[12] ),
    .S(_246_),
    .Z(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _552_ (
    .I0(debug_rdata_i[13]),
    .I1(\debug_read_latch[13] ),
    .S(_246_),
    .Z(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _553_ (
    .I0(debug_rdata_i[14]),
    .I1(\debug_read_latch[14] ),
    .S(_246_),
    .Z(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _554_ (
    .I0(debug_rdata_i[15]),
    .I1(\debug_read_latch[15] ),
    .S(_246_),
    .Z(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _555_ (
    .A1(_102_),
    .A2(din_valid_i),
    .A3(_153_),
    .ZN(_247_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _556_ (
    .A1(\debug_data_hi[0] ),
    .A2(_247_),
    .ZN(_248_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _557_ (
    .A1(_117_),
    .A2(_247_),
    .B(_248_),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _558_ (
    .A1(\debug_data_hi[1] ),
    .A2(_247_),
    .ZN(_249_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _559_ (
    .A1(_114_),
    .A2(_247_),
    .B(_249_),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _560_ (
    .A1(\debug_data_hi[2] ),
    .A2(_247_),
    .ZN(_250_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _561_ (
    .A1(_113_),
    .A2(_247_),
    .B(_250_),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _562_ (
    .I0(din[3]),
    .I1(\debug_data_hi[3] ),
    .S(_247_),
    .Z(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _563_ (
    .A1(\debug_data_hi[4] ),
    .A2(_247_),
    .ZN(_251_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _564_ (
    .A1(_115_),
    .A2(_247_),
    .B(_251_),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _565_ (
    .A1(\debug_data_hi[5] ),
    .A2(_247_),
    .ZN(_252_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _566_ (
    .A1(_116_),
    .A2(_247_),
    .B(_252_),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _567_ (
    .I0(din[6]),
    .I1(\debug_data_hi[6] ),
    .S(_247_),
    .Z(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _568_ (
    .A1(\debug_data_hi[7] ),
    .A2(_247_),
    .ZN(_253_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _569_ (
    .A1(_118_),
    .A2(_247_),
    .B(_253_),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _570_ (
    .A1(_134_),
    .A2(_144_),
    .A3(external_fire),
    .ZN(_254_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _571_ (
    .A1(\echo_data[0] ),
    .A2(_254_),
    .ZN(_255_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _572_ (
    .A1(_117_),
    .A2(_254_),
    .B(_255_),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _573_ (
    .A1(\echo_data[1] ),
    .A2(_254_),
    .ZN(_256_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _574_ (
    .A1(_114_),
    .A2(_254_),
    .B(_256_),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _575_ (
    .A1(\echo_data[2] ),
    .A2(_254_),
    .ZN(_257_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _576_ (
    .A1(_113_),
    .A2(_254_),
    .B(_257_),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _577_ (
    .I0(din[3]),
    .I1(\echo_data[3] ),
    .S(_254_),
    .Z(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _578_ (
    .A1(\echo_data[4] ),
    .A2(_254_),
    .ZN(_258_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _579_ (
    .A1(_115_),
    .A2(_254_),
    .B(_258_),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _580_ (
    .A1(\echo_data[5] ),
    .A2(_254_),
    .ZN(_259_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _581_ (
    .A1(_116_),
    .A2(_254_),
    .B(_259_),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _582_ (
    .I0(din[6]),
    .I1(\echo_data[6] ),
    .S(_254_),
    .Z(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _583_ (
    .A1(\echo_data[7] ),
    .A2(_254_),
    .ZN(_260_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _584_ (
    .A1(_118_),
    .A2(_254_),
    .B(_260_),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _585_ (
    .A1(\magic_index[1] ),
    .A2(\magic_index[0] ),
    .A3(_121_),
    .ZN(_261_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _586_ (
    .A1(_173_),
    .A2(_261_),
    .Z(_262_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _587_ (
    .A1(_173_),
    .A2(_261_),
    .ZN(_263_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _588_ (
    .A1(_114_),
    .A2(ext_state[0]),
    .ZN(_264_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _589_ (
    .A1(_185_),
    .A2(_264_),
    .ZN(_265_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _590_ (
    .A1(din[1]),
    .A2(din[0]),
    .A3(_179_),
    .A4(_185_),
    .ZN(_266_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _591_ (
    .A1(_114_),
    .A2(_117_),
    .ZN(_267_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _592_ (
    .A1(_158_),
    .A2(_266_),
    .B(_263_),
    .ZN(_268_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _593_ (
    .A1(\magic_index[0] ),
    .A2(_268_),
    .ZN(_269_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _594_ (
    .A1(\magic_index[0] ),
    .A2(_173_),
    .ZN(_270_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _595_ (
    .A1(\magic_index[0] ),
    .A2(_268_),
    .B(_270_),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _596_ (
    .A1(_119_),
    .A2(_120_),
    .B(_173_),
    .ZN(_271_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _597_ (
    .A1(_119_),
    .A2(_269_),
    .B1(_271_),
    .B2(_268_),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _598_ (
    .A1(_268_),
    .A2(_271_),
    .B(_121_),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _599_ (
    .A1(serializer_job_done_i),
    .A2(standalone_active_o),
    .B(_103_),
    .ZN(_272_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _600_ (
    .A1(_194_),
    .A2(_272_),
    .ZN(_273_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _601_ (
    .A1(_136_),
    .A2(_190_),
    .A3(_202_),
    .ZN(_274_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _602_ (
    .I0(standalone_active_o),
    .I1(_274_),
    .S(_273_),
    .Z(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _603_ (
    .A1(din_valid_i),
    .A2(_151_),
    .ZN(_275_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _604_ (
    .A1(debug_addr_o[0]),
    .A2(_275_),
    .ZN(_276_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _605_ (
    .A1(_117_),
    .A2(_275_),
    .B(_276_),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _606_ (
    .A1(debug_addr_o[1]),
    .A2(_275_),
    .ZN(_277_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _607_ (
    .A1(_114_),
    .A2(_275_),
    .B(_277_),
    .ZN(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _608_ (
    .A1(debug_addr_o[2]),
    .A2(_275_),
    .ZN(_278_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _609_ (
    .A1(_113_),
    .A2(_275_),
    .B(_278_),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _610_ (
    .I0(din[3]),
    .I1(debug_addr_o[3]),
    .S(_275_),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _611_ (
    .A1(debug_addr_o[4]),
    .A2(_275_),
    .ZN(_279_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _612_ (
    .A1(_115_),
    .A2(_275_),
    .B(_279_),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _613_ (
    .A1(debug_addr_o[5]),
    .A2(_275_),
    .ZN(_280_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _614_ (
    .A1(_116_),
    .A2(_275_),
    .B(_280_),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _615_ (
    .I0(din[6]),
    .I1(debug_addr_o[6]),
    .S(_275_),
    .Z(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _616_ (
    .A1(debug_addr_o[7]),
    .A2(_275_),
    .ZN(_281_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _617_ (
    .A1(_118_),
    .A2(_275_),
    .B(_281_),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _618_ (
    .A1(_152_),
    .A2(_158_),
    .A3(_163_),
    .ZN(_282_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _619_ (
    .A1(debug_wdata_o[0]),
    .A2(_282_),
    .ZN(_283_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _620_ (
    .A1(_117_),
    .A2(_282_),
    .B(_283_),
    .ZN(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _621_ (
    .A1(debug_wdata_o[1]),
    .A2(_282_),
    .ZN(_284_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _622_ (
    .A1(_114_),
    .A2(_282_),
    .B(_284_),
    .ZN(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _623_ (
    .A1(debug_wdata_o[2]),
    .A2(_282_),
    .ZN(_285_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _624_ (
    .A1(_113_),
    .A2(_282_),
    .B(_285_),
    .ZN(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _625_ (
    .I0(debug_wdata_o[3]),
    .I1(din[3]),
    .S(_282_),
    .Z(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _626_ (
    .A1(debug_wdata_o[4]),
    .A2(_282_),
    .ZN(_286_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _627_ (
    .A1(_115_),
    .A2(_282_),
    .B(_286_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _628_ (
    .A1(debug_wdata_o[5]),
    .A2(_282_),
    .ZN(_287_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _629_ (
    .A1(_116_),
    .A2(_282_),
    .B(_287_),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _630_ (
    .I0(debug_wdata_o[6]),
    .I1(din[6]),
    .S(_282_),
    .Z(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _631_ (
    .A1(debug_wdata_o[7]),
    .A2(_282_),
    .ZN(_288_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _632_ (
    .A1(_118_),
    .A2(_282_),
    .B(_288_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _633_ (
    .I0(debug_wdata_o[8]),
    .I1(\debug_data_hi[0] ),
    .S(_282_),
    .Z(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _634_ (
    .I0(debug_wdata_o[9]),
    .I1(\debug_data_hi[1] ),
    .S(_282_),
    .Z(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _635_ (
    .I0(debug_wdata_o[10]),
    .I1(\debug_data_hi[2] ),
    .S(_282_),
    .Z(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _636_ (
    .I0(debug_wdata_o[11]),
    .I1(\debug_data_hi[3] ),
    .S(_282_),
    .Z(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _637_ (
    .I0(debug_wdata_o[12]),
    .I1(\debug_data_hi[4] ),
    .S(_282_),
    .Z(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _638_ (
    .I0(debug_wdata_o[13]),
    .I1(\debug_data_hi[5] ),
    .S(_282_),
    .Z(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _639_ (
    .I0(debug_wdata_o[14]),
    .I1(\debug_data_hi[6] ),
    .S(_282_),
    .Z(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _640_ (
    .I0(debug_wdata_o[15]),
    .I1(\debug_data_hi[7] ),
    .S(_282_),
    .Z(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _641_ (
    .A1(top_state_o[2]),
    .A2(debug_rvalid_i),
    .A3(_208_),
    .B1(_207_),
    .B2(debug_ready_i),
    .ZN(_289_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _642_ (
    .A1(_106_),
    .A2(_157_),
    .B(_262_),
    .C(_289_),
    .ZN(_290_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _643_ (
    .A1(_162_),
    .A2(_165_),
    .B(_180_),
    .C(_290_),
    .ZN(_291_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi221_1 _644_ (
    .A1(top_state_o[3]),
    .A2(_171_),
    .B1(_179_),
    .B2(_191_),
    .C(_149_),
    .ZN(_292_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _645_ (
    .A1(din[1]),
    .A2(_117_),
    .ZN(_293_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _646_ (
    .A1(_113_),
    .A2(ext_state[0]),
    .A3(_182_),
    .A4(_183_),
    .ZN(_294_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _647_ (
    .A1(_293_),
    .A2(_294_),
    .ZN(_295_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _648_ (
    .A1(_265_),
    .A2(_292_),
    .A3(_295_),
    .ZN(_296_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _649_ (
    .I0(_296_),
    .I1(top_state_o[0]),
    .S(_291_),
    .Z(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _650_ (
    .A1(_147_),
    .A2(_163_),
    .B(_150_),
    .ZN(_297_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _651_ (
    .A1(_181_),
    .A2(_272_),
    .B(_297_),
    .ZN(_298_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _652_ (
    .A1(din[1]),
    .A2(din[0]),
    .ZN(_299_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _653_ (
    .A1(_185_),
    .A2(_264_),
    .B1(_294_),
    .B2(_114_),
    .ZN(_300_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _654_ (
    .A1(_267_),
    .A2(_300_),
    .B(_298_),
    .ZN(_301_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _655_ (
    .I0(_301_),
    .I1(top_state_o[1]),
    .S(_291_),
    .Z(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _656_ (
    .A1(_294_),
    .A2(_299_),
    .B(_157_),
    .C(debug_write_o),
    .ZN(_302_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _657_ (
    .A1(_266_),
    .A2(_302_),
    .ZN(_303_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _658_ (
    .I0(_303_),
    .I1(top_state_o[2]),
    .S(_291_),
    .Z(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _659_ (
    .A1(_155_),
    .A2(_170_),
    .A3(debug_mode_o),
    .ZN(_304_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _660_ (
    .A1(_295_),
    .A2(_304_),
    .ZN(_305_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _661_ (
    .I0(_305_),
    .I1(top_state_o[3]),
    .S(_291_),
    .Z(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _662_ (
    .A1(_181_),
    .A2(_194_),
    .B(core_ofdm_active),
    .ZN(_306_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _663_ (
    .A1(_181_),
    .A2(_194_),
    .A3(_205_),
    .B(_306_),
    .ZN(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _664_ (
    .A1(job_head_command[0]),
    .A2(_193_),
    .ZN(_307_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _665_ (
    .A1(_117_),
    .A2(_193_),
    .B(_307_),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _666_ (
    .A1(job_head_command[1]),
    .A2(_193_),
    .ZN(_308_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _667_ (
    .A1(_114_),
    .A2(_193_),
    .B(_308_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _668_ (
    .A1(job_head_command[2]),
    .A2(_193_),
    .ZN(_309_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _669_ (
    .A1(_113_),
    .A2(_193_),
    .B(_309_),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _670_ (
    .A1(din[3]),
    .A2(_193_),
    .ZN(_310_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _671_ (
    .A1(_100_),
    .A2(_193_),
    .B(_310_),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _672_ (
    .A1(job_head_command[4]),
    .A2(_193_),
    .ZN(_311_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _673_ (
    .A1(_115_),
    .A2(_193_),
    .B(_311_),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _674_ (
    .A1(job_head_command[5]),
    .A2(_193_),
    .ZN(_312_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _675_ (
    .A1(_116_),
    .A2(_193_),
    .B(_312_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _676_ (
    .A1(din[6]),
    .A2(_193_),
    .ZN(_313_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _677_ (
    .A1(_101_),
    .A2(_193_),
    .B(_313_),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _678_ (
    .A1(job_head_command[7]),
    .A2(_193_),
    .ZN(_314_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _679_ (
    .A1(_118_),
    .A2(_193_),
    .B(_314_),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _680_ (
    .A1(_158_),
    .A2(_206_),
    .ZN(_315_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _681_ (
    .A1(top_state_o[0]),
    .A2(_107_),
    .A3(_315_),
    .ZN(_316_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _682_ (
    .A1(_107_),
    .A2(_315_),
    .B(_316_),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _683_ (
    .A1(\input_left[0] ),
    .A2(\input_left[1] ),
    .ZN(_317_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _684_ (
    .A1(\input_left[0] ),
    .A2(\input_left[1] ),
    .Z(_318_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _685_ (
    .A1(_165_),
    .A2(_189_),
    .ZN(_319_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _686_ (
    .A1(_113_),
    .A2(din[0]),
    .A3(_319_),
    .B1(_318_),
    .B2(_165_),
    .ZN(_320_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _687_ (
    .I0(\input_left[1] ),
    .I1(_320_),
    .S(_315_),
    .Z(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _688_ (
    .A1(_108_),
    .A2(_317_),
    .ZN(_321_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _689_ (
    .A1(_108_),
    .A2(_317_),
    .Z(_322_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _690_ (
    .A1(_267_),
    .A2(_299_),
    .ZN(_323_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _691_ (
    .A1(_165_),
    .A2(_322_),
    .B1(_323_),
    .B2(_319_),
    .ZN(_324_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _692_ (
    .I0(\input_left[2] ),
    .I1(_324_),
    .S(_315_),
    .Z(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _693_ (
    .A1(din[2]),
    .A2(_189_),
    .A3(_293_),
    .ZN(_325_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _694_ (
    .A1(_165_),
    .A2(_187_),
    .A3(_325_),
    .ZN(_326_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _695_ (
    .A1(_321_),
    .A2(_326_),
    .B(_158_),
    .C(_206_),
    .ZN(_327_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _696_ (
    .A1(_108_),
    .A2(_109_),
    .A3(_317_),
    .ZN(_328_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _697_ (
    .A1(_164_),
    .A2(_328_),
    .ZN(_329_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _698_ (
    .A1(_315_),
    .A2(_326_),
    .A3(_329_),
    .ZN(_330_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _699_ (
    .A1(_109_),
    .A2(_327_),
    .B(_330_),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _700_ (
    .A1(\input_left[4] ),
    .A2(_328_),
    .B(_164_),
    .ZN(_331_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _701_ (
    .A1(_315_),
    .A2(_331_),
    .Z(_332_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _702_ (
    .A1(\input_left[4] ),
    .A2(_328_),
    .B1(_331_),
    .B2(_315_),
    .ZN(_333_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _703_ (
    .A1(_203_),
    .A2(_326_),
    .ZN(_334_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _704_ (
    .A1(_111_),
    .A2(_315_),
    .B1(_333_),
    .B2(_334_),
    .ZN(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _705_ (
    .A1(_108_),
    .A2(_109_),
    .A3(_159_),
    .A4(_317_),
    .ZN(_335_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _706_ (
    .A1(_158_),
    .A2(_206_),
    .A3(_335_),
    .ZN(_336_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _707_ (
    .A1(_158_),
    .A2(_165_),
    .A3(_335_),
    .B1(_332_),
    .B2(_110_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _708_ (
    .A1(\input_left[6] ),
    .A2(_158_),
    .A3(_206_),
    .A4(_335_),
    .ZN(_337_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _709_ (
    .A1(\input_left[6] ),
    .A2(_336_),
    .ZN(_338_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _710_ (
    .A1(_165_),
    .A2(_315_),
    .B(_338_),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _711_ (
    .A1(\input_left[7] ),
    .A2(_337_),
    .ZN(_339_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _712_ (
    .A1(_165_),
    .A2(_315_),
    .B(_339_),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _713_ (
    .A1(_113_),
    .A2(_323_),
    .B(_202_),
    .ZN(_340_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _714_ (
    .A1(_159_),
    .A2(_160_),
    .A3(_317_),
    .ZN(_341_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _715_ (
    .A1(\input_left[8] ),
    .A2(_341_),
    .Z(_342_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _716_ (
    .A1(_319_),
    .A2(_340_),
    .B1(_342_),
    .B2(_165_),
    .ZN(_343_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _717_ (
    .I0(\input_left[8] ),
    .I1(_343_),
    .S(_315_),
    .Z(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _718_ (
    .A1(_131_),
    .A2(_136_),
    .ZN(_344_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _719_ (
    .A1(_131_),
    .A2(_136_),
    .B(_194_),
    .ZN(_345_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _720_ (
    .A1(_136_),
    .A2(_193_),
    .B(_344_),
    .C(_192_),
    .ZN(_346_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _721_ (
    .A1(core_dout_valid_i),
    .A2(drain_active),
    .ZN(_347_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _722_ (
    .A1(\output_left[0] ),
    .A2(_346_),
    .ZN(_348_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _723_ (
    .A1(\output_left[0] ),
    .A2(_347_),
    .B(_348_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _724_ (
    .A1(_137_),
    .A2(_186_),
    .ZN(_349_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _725_ (
    .A1(\output_left[1] ),
    .A2(\output_left[0] ),
    .Z(_350_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _726_ (
    .A1(din[0]),
    .A2(_349_),
    .B1(_350_),
    .B2(_137_),
    .ZN(_351_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _727_ (
    .I0(_351_),
    .I1(\output_left[1] ),
    .S(_346_),
    .Z(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _728_ (
    .A1(\output_left[2] ),
    .A2(_195_),
    .ZN(_352_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _729_ (
    .A1(_117_),
    .A2(_349_),
    .B1(_352_),
    .B2(_137_),
    .ZN(_353_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _730_ (
    .I0(_353_),
    .I1(\output_left[2] ),
    .S(_346_),
    .Z(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _731_ (
    .A1(\output_left[1] ),
    .A2(\output_left[0] ),
    .A3(\output_left[2] ),
    .B(\output_left[3] ),
    .ZN(_354_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _732_ (
    .A1(_136_),
    .A2(_196_),
    .A3(_354_),
    .ZN(_355_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _733_ (
    .A1(_204_),
    .A2(_355_),
    .ZN(_356_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _734_ (
    .A1(\output_left[3] ),
    .A2(_346_),
    .ZN(_357_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _735_ (
    .A1(_346_),
    .A2(_356_),
    .B(_357_),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _736_ (
    .A1(\output_left[4] ),
    .A2(_346_),
    .ZN(_358_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _737_ (
    .A1(_205_),
    .A2(_346_),
    .B(_358_),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _738_ (
    .A1(_200_),
    .A2(_346_),
    .B(\output_left[5] ),
    .ZN(_359_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _739_ (
    .A1(_099_),
    .A2(_199_),
    .ZN(_360_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _740_ (
    .A1(_347_),
    .A2(_360_),
    .B(_359_),
    .ZN(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or3_1 _741_ (
    .A1(\output_left[6] ),
    .A2(_346_),
    .A3(_360_),
    .Z(_361_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _742_ (
    .A1(_097_),
    .A2(_360_),
    .B(_136_),
    .ZN(_362_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _743_ (
    .A1(_097_),
    .A2(_361_),
    .B1(_362_),
    .B2(_345_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _744_ (
    .A1(\output_left[6] ),
    .A2(_098_),
    .A3(_360_),
    .B(_136_),
    .ZN(_363_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _745_ (
    .A1(_098_),
    .A2(_361_),
    .B1(_363_),
    .B2(_345_),
    .ZN(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _746_ (
    .A1(_129_),
    .A2(_197_),
    .ZN(_364_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _747_ (
    .A1(\output_left[8] ),
    .A2(_364_),
    .Z(_365_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _748_ (
    .A1(_137_),
    .A2(_365_),
    .B(_349_),
    .ZN(_366_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _749_ (
    .I0(_366_),
    .I1(\output_left[8] ),
    .S(_346_),
    .Z(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _750_ (
    .I0(debug_rdata_i[0]),
    .I1(\debug_read_latch[0] ),
    .S(_246_),
    .Z(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _751_ (
    .I0(debug_rdata_i[1]),
    .I1(\debug_read_latch[1] ),
    .S(_246_),
    .Z(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_2 _752_ (
    .I0(debug_rdata_i[2]),
    .I1(\debug_read_latch[2] ),
    .S(_246_),
    .Z(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _753_ (
    .CLK(clk),
    .D(_035_),
    .Q(standalone_active_o),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _754_ (
    .CLK(clk),
    .D(_036_),
    .Q(debug_addr_o[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _755_ (
    .CLK(clk),
    .D(_037_),
    .Q(debug_addr_o[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _756_ (
    .CLK(clk),
    .D(_038_),
    .Q(debug_addr_o[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _757_ (
    .CLK(clk),
    .D(_039_),
    .Q(debug_addr_o[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _758_ (
    .CLK(clk),
    .D(_040_),
    .Q(debug_addr_o[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _759_ (
    .CLK(clk),
    .D(_041_),
    .Q(debug_addr_o[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _760_ (
    .CLK(clk),
    .D(_042_),
    .Q(debug_addr_o[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _761_ (
    .CLK(clk),
    .D(_043_),
    .Q(debug_addr_o[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _762_ (
    .CLK(clk),
    .D(_044_),
    .Q(debug_wdata_o[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _763_ (
    .CLK(clk),
    .D(_045_),
    .Q(debug_wdata_o[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _764_ (
    .CLK(clk),
    .D(_046_),
    .Q(debug_wdata_o[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _765_ (
    .CLK(clk),
    .D(_047_),
    .Q(debug_wdata_o[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _766_ (
    .CLK(clk),
    .D(_048_),
    .Q(debug_wdata_o[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _767_ (
    .CLK(clk),
    .D(_049_),
    .Q(debug_wdata_o[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _768_ (
    .CLK(clk),
    .D(_050_),
    .Q(debug_wdata_o[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _769_ (
    .CLK(clk),
    .D(_051_),
    .Q(debug_wdata_o[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _770_ (
    .CLK(clk),
    .D(_052_),
    .Q(debug_wdata_o[8]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _771_ (
    .CLK(clk),
    .D(_053_),
    .Q(debug_wdata_o[9]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _772_ (
    .CLK(clk),
    .D(_054_),
    .Q(debug_wdata_o[10]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _773_ (
    .CLK(clk),
    .D(_055_),
    .Q(debug_wdata_o[11]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _774_ (
    .CLK(clk),
    .D(_056_),
    .Q(debug_wdata_o[12]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _775_ (
    .CLK(clk),
    .D(_057_),
    .Q(debug_wdata_o[13]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _776_ (
    .CLK(clk),
    .D(_058_),
    .Q(debug_wdata_o[14]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _777_ (
    .CLK(clk),
    .D(_059_),
    .Q(debug_wdata_o[15]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _778_ (
    .CLK(clk),
    .D(_060_),
    .Q(top_state_o[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _779_ (
    .CLK(clk),
    .D(_061_),
    .Q(top_state_o[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _780_ (
    .CLK(clk),
    .D(_062_),
    .Q(top_state_o[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _781_ (
    .CLK(clk),
    .D(_063_),
    .Q(top_state_o[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _782_ (
    .CLK(clk),
    .D(_064_),
    .Q(top_state_o[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _783_ (
    .CLK(clk),
    .D(_065_),
    .Q(core_ofdm_active),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _784_ (
    .CLK(clk),
    .D(_066_),
    .Q(job_head_command[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _785_ (
    .CLK(clk),
    .D(_067_),
    .Q(job_head_command[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _786_ (
    .CLK(clk),
    .D(_068_),
    .Q(job_head_command[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _787_ (
    .CLK(clk),
    .D(_069_),
    .Q(job_head_command[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _788_ (
    .CLK(clk),
    .D(_070_),
    .Q(job_head_command[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _789_ (
    .CLK(clk),
    .D(_071_),
    .Q(job_head_command[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _790_ (
    .CLK(clk),
    .D(_072_),
    .Q(job_head_command[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _791_ (
    .CLK(clk),
    .D(_073_),
    .Q(job_head_command[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _792_ (
    .CLK(clk),
    .D(_074_),
    .Q(\input_left[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _793_ (
    .CLK(clk),
    .D(_075_),
    .Q(\input_left[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _794_ (
    .CLK(clk),
    .D(_076_),
    .Q(\input_left[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _795_ (
    .CLK(clk),
    .D(_077_),
    .Q(\input_left[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _796_ (
    .CLK(clk),
    .D(_078_),
    .Q(\input_left[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _797_ (
    .CLK(clk),
    .D(_079_),
    .Q(\input_left[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _798_ (
    .CLK(clk),
    .D(_080_),
    .Q(\input_left[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _799_ (
    .CLK(clk),
    .D(_081_),
    .Q(\input_left[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _800_ (
    .CLK(clk),
    .D(_082_),
    .Q(\input_left[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _801_ (
    .CLK(clk),
    .D(_083_),
    .Q(\output_left[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _802_ (
    .CLK(clk),
    .D(_084_),
    .Q(\output_left[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _803_ (
    .CLK(clk),
    .D(_085_),
    .Q(\output_left[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _804_ (
    .CLK(clk),
    .D(_086_),
    .Q(\output_left[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _805_ (
    .CLK(clk),
    .D(_087_),
    .Q(\output_left[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _806_ (
    .CLK(clk),
    .D(_088_),
    .Q(\output_left[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _807_ (
    .CLK(clk),
    .D(_089_),
    .Q(\output_left[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _808_ (
    .CLK(clk),
    .D(_090_),
    .Q(\output_left[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _809_ (
    .CLK(clk),
    .D(_091_),
    .Q(\output_left[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _810_ (
    .CLK(clk),
    .D(_092_),
    .Q(\debug_read_latch[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _811_ (
    .CLK(clk),
    .D(_093_),
    .Q(\debug_read_latch[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _812_ (
    .CLK(clk),
    .D(_094_),
    .Q(\debug_read_latch[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _813_ (
    .CLK(clk),
    .D(_003_),
    .Q(\debug_read_latch[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _814_ (
    .CLK(clk),
    .D(_004_),
    .Q(\debug_read_latch[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _815_ (
    .CLK(clk),
    .D(_005_),
    .Q(\debug_read_latch[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _816_ (
    .CLK(clk),
    .D(_006_),
    .Q(\debug_read_latch[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _817_ (
    .CLK(clk),
    .D(_007_),
    .Q(\debug_read_latch[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _818_ (
    .CLK(clk),
    .D(_008_),
    .Q(\debug_read_latch[8] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _819_ (
    .CLK(clk),
    .D(_009_),
    .Q(\debug_read_latch[9] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _820_ (
    .CLK(clk),
    .D(_010_),
    .Q(\debug_read_latch[10] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _821_ (
    .CLK(clk),
    .D(_011_),
    .Q(\debug_read_latch[11] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _822_ (
    .CLK(clk),
    .D(_012_),
    .Q(\debug_read_latch[12] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _823_ (
    .CLK(clk),
    .D(_013_),
    .Q(\debug_read_latch[13] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _824_ (
    .CLK(clk),
    .D(_014_),
    .Q(\debug_read_latch[14] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _825_ (
    .CLK(clk),
    .D(_015_),
    .Q(\debug_read_latch[15] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _826_ (
    .CLK(clk),
    .D(_016_),
    .Q(\debug_data_hi[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _827_ (
    .CLK(clk),
    .D(_017_),
    .Q(\debug_data_hi[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _828_ (
    .CLK(clk),
    .D(_018_),
    .Q(\debug_data_hi[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _829_ (
    .CLK(clk),
    .D(_019_),
    .Q(\debug_data_hi[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _830_ (
    .CLK(clk),
    .D(_020_),
    .Q(\debug_data_hi[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _831_ (
    .CLK(clk),
    .D(_021_),
    .Q(\debug_data_hi[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _832_ (
    .CLK(clk),
    .D(_022_),
    .Q(\debug_data_hi[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _833_ (
    .CLK(clk),
    .D(_023_),
    .Q(\debug_data_hi[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _834_ (
    .CLK(clk),
    .D(_024_),
    .Q(\echo_data[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _835_ (
    .CLK(clk),
    .D(_025_),
    .Q(\echo_data[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _836_ (
    .CLK(clk),
    .D(_026_),
    .Q(\echo_data[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _837_ (
    .CLK(clk),
    .D(_027_),
    .Q(\echo_data[3] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _838_ (
    .CLK(clk),
    .D(_028_),
    .Q(\echo_data[4] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _839_ (
    .CLK(clk),
    .D(_029_),
    .Q(\echo_data[5] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _840_ (
    .CLK(clk),
    .D(_030_),
    .Q(\echo_data[6] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _841_ (
    .CLK(clk),
    .D(_031_),
    .Q(\echo_data[7] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _842_ (
    .CLK(clk),
    .D(_032_),
    .Q(\magic_index[0] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _843_ (
    .CLK(clk),
    .D(_033_),
    .Q(\magic_index[1] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _844_ (
    .CLK(clk),
    .D(_034_),
    .Q(\magic_index[2] ),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _845_ (
    .CLK(clk),
    .D(_002_),
    .Q(job_push),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _846_ (
    .CLK(clk),
    .D(_000_),
    .Q(core_rx_complete),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _847_ (
    .CLK(clk),
    .D(_001_),
    .Q(core_tx_complete),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _848_ (
    .ZN(ext_state[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel _849_ (
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__buf_1 _850_ (
    .I(core_rx_complete),
    .Z(core_rx_selected_complete)
  );
endmodule
