`default_nettype none

// Physical-half-word TX reader. I and Q are fetched on consecutive clocks;
// the CP is generated by rereading the final body samples.
module tdiq_output_cp_insert_sram #(
    parameter integer BYTE_INTERVAL = 1
) (
    input logic clk, input logic rst_n,
    input logic start_i, input logic [3:0] cp_length_i,
    output logic mem_req_o, output logic [7:0] mem_addr_o,
    input logic mem_ready_i, input logic [15:0] mem_rdata_i,
    input logic mem_rvalid_i,
    output logic [7:0] dout, output logic dout_valid_o,
    output logic busy_o, output logic done_o
);
    logic [7:0] request_sample;
    logic request_q;
    logic [8:0] requests_left, responses_left;
    localparam integer PACE_WIDTH = (BYTE_INTERVAL <= 1) ? 1 : $clog2(BYTE_INTERVAL);
    logic [PACE_WIDTH-1:0] pace_count;

    function automatic logic [7:0] saturate_q17_to_byte(input logic signed [15:0] value);
        begin
            if (value > 16'sd127) saturate_q17_to_byte = 8'h7f;
            else if (value < -16'sd128) saturate_q17_to_byte = 8'h80;
            else saturate_q17_to_byte = value[7:0];
        end
    endfunction

    assign mem_req_o = busy_o && (requests_left != 0) && (pace_count == 0);
    assign mem_addr_o = {request_sample[6:0],request_q};

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            request_sample<=0; request_q<=0; requests_left<=0; responses_left<=0;
            pace_count<=0; busy_o<=0; done_o<=0; dout<=0; dout_valid_o<=0;
        end else begin
            done_o<=0; dout_valid_o<=0;
            if (pace_count != 0) pace_count <= pace_count-1'b1;
            if (start_i && !busy_o) begin
                request_sample <= 8'd128-{4'd0,cp_length_i};
                request_q <= 0;
                requests_left <= ({5'd0,cp_length_i}+9'd128)<<1;
                responses_left <= ({5'd0,cp_length_i}+9'd128)<<1;
                pace_count <= 0;
                busy_o <= 1;
            end else if (busy_o) begin
                if (mem_req_o && mem_ready_i) begin
                    requests_left <= requests_left-1'b1;
                    if (BYTE_INTERVAL > 1) pace_count <= BYTE_INTERVAL-1;
                    if (!request_q) request_q<=1;
                    else begin
                        request_q<=0;
                        request_sample <= request_sample==8'd127 ? 8'd0 : request_sample+1'b1;
                    end
                end
                if (mem_rvalid_i) begin
                    dout <= saturate_q17_to_byte($signed(mem_rdata_i));
                    dout_valid_o <= 1;
                    responses_left <= responses_left-1'b1;
                    if (responses_left==9'd1) begin busy_o<=0; done_o<=1; end
                end
            end
        end
    end
endmodule

`default_nettype wire
