`timescale 1ns/1ps
`default_nettype none

// Physical-half-word TX reader. I and Q are fetched on consecutive clocks;
// the CP is generated by rereading the final body samples.
//
// Output handshake: dout is held until dout_valid_o && dout_ready_i.
// Always-ready BYTE_INTERVAL cadence matches the previous request-paced
// production behavior (visible valid-to-valid == BYTE_INTERVAL).
// While the downstream stalls, the pace counter freezes so the stream cannot
// catch up after ready returns.
module tdiq_output_cp_insert_sram #(
    parameter integer BYTE_INTERVAL = 1
) (
    input logic clk, input logic rst_n,
    input logic start_i, input logic [3:0] cp_length_i,
    output logic mem_req_o, output logic [7:0] mem_addr_o,
    input logic mem_ready_i, input logic [15:0] mem_rdata_i,
    input logic mem_rvalid_i,
    output logic [7:0] dout, output logic dout_valid_o,
    input logic dout_ready_i,
    output logic busy_o, output logic done_o
);
    logic [7:0] request_sample;
    logic request_q;
    logic [8:0] requests_left, responses_left;
    localparam integer PACE_WIDTH = (BYTE_INTERVAL <= 1) ? 1 : $clog2(BYTE_INTERVAL);
    logic [PACE_WIDTH-1:0] pace_count;
    logic inflight;
    logic skid_valid;
    logic [7:0] skid_data;
    logic last_byte_pending;

    wire dout_fire = dout_valid_o && dout_ready_i;
    wire stall_hold = dout_valid_o && !dout_ready_i;
    wire inflight_busy = inflight && !mem_rvalid_i;
    wire output_room = !dout_valid_o || dout_ready_i;

    // BYTE_INTERVAL==1: prefetch when the current byte will handshake or the
    // output register is empty.  One skid word covers a stall overlapping an
    // already-issued SRAM read.
    // BYTE_INTERVAL>1: keep original request pacing, but never issue while a
    // byte is still pending on dout.
    wire can_issue = busy_o && (requests_left != 0) && (pace_count == 0)
        && !skid_valid
        && ((BYTE_INTERVAL <= 1)
            ? (output_room && !inflight_busy)
            : (!dout_valid_o && !inflight));

    function automatic logic [7:0] saturate_q17_to_byte(input logic signed [15:0] value);
        begin
            if (value > 16'sd127) saturate_q17_to_byte = 8'h7f;
            else if (value < -16'sd128) saturate_q17_to_byte = 8'h80;
            else saturate_q17_to_byte = value[7:0];
        end
    endfunction

    assign mem_req_o = can_issue;
    assign mem_addr_o = {request_sample[6:0],request_q};

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            request_sample<=0; request_q<=0; requests_left<=0; responses_left<=0;
            pace_count<=0; busy_o<=0; done_o<=0; dout<=0; dout_valid_o<=0;
            inflight<=0; skid_valid<=0; skid_data<=0; last_byte_pending<=0;
        end else begin
            done_o<=0;
            if (start_i && !busy_o) begin
                request_sample <= 8'd64-{4'd0,cp_length_i};
                request_q <= 0;
                requests_left <= ({5'd0,cp_length_i}+9'd64)<<1;
                responses_left <= ({5'd0,cp_length_i}+9'd64)<<1;
                pace_count <= 0;
                busy_o <= 1;
                inflight <= 0;
                skid_valid <= 0;
                last_byte_pending <= 0;
                dout_valid_o <= 0;
            end else if (busy_o) begin
                if ((pace_count != 0) && !stall_hold)
                    pace_count <= pace_count-1'b1;

                if (mem_req_o && mem_ready_i) begin
                    requests_left <= requests_left-1'b1;
                    inflight <= 1'b1;
                    if (BYTE_INTERVAL > 1)
                        pace_count <= BYTE_INTERVAL-1;
                    if (!request_q) request_q<=1;
                    else begin
                        request_q<=0;
                        request_sample <= request_sample==8'd63 ? 8'd0 : request_sample+1'b1;
                    end
                end else if (mem_rvalid_i) begin
                    inflight <= 1'b0;
                end

                if (mem_rvalid_i) begin
                    responses_left <= responses_left-1'b1;
                    if (responses_left==9'd1)
                        last_byte_pending <= 1'b1;
                    if (!dout_valid_o || dout_fire) begin
                        dout <= saturate_q17_to_byte($signed(mem_rdata_i));
                        dout_valid_o <= 1'b1;
                    end else begin
                        skid_data <= saturate_q17_to_byte($signed(mem_rdata_i));
                        skid_valid <= 1'b1;
                    end
                end else if (dout_fire) begin
                    if (skid_valid) begin
                        dout <= skid_data;
                        skid_valid <= 1'b0;
                    end else begin
                        dout_valid_o <= 1'b0;
                        if (last_byte_pending) begin
                            busy_o <= 1'b0;
                            done_o <= 1'b1;
                            last_byte_pending <= 1'b0;
                        end
                    end
                end
            end
        end
    end
endmodule

`default_nettype wire
